### ISSUE TITLE
Question: How to combine upload

### ISSUE THREAD

**Issue by Bo0km4n** [embulk/embulk#1013]
embulk 0.9.4

Hi, I'm always using embulk for work.
Today, I want to tell me how to combined upload.

Embulk read input data from any services, and then split data into several pages.
After that, Embulk processes the data for each page.
When uploading data to the storage service, it is divided into multiple files.
I would like to combine the split original data into one file and upload it.

Here is an actual example.

```
in: 
 type: s3
 path: hoge/fuga

fuga
├── sample_1.csv
├── sample_10.csv
├── sample_2.csv
├── sample_3.csv
├── sample_4.csv
├── sample_5.csv
├── sample_6.csv
├── sample_7.csv
├── sample_8.csv
└── sample_9.csv

out:
  type: s3
  path: foo/bar

expect output
bar
└── combined_data.csv
```

If there is person who has knowledge about this, please tell me :bow:

**Comment by hiroyuki-sato** [comment]
Hello, @Bo0km4n 

As far as I know, It's in a feature request. #546 (It's impossible yet).

Can you tell us your use case for future discussion?

**Comment by Bo0km4n** [comment]
Thanks for telling issue link.

Use case is for example,
Suppose that customer's data is stored in s3.
The data in s3 is divided as in the example above.
We may want to export that data to customer's services (s3, gcs, dropbox, googledrive).

**Comment by Bo0km4n** [comment]
Thanks. 
I will consider whether it can be realized by the method you taught.
