### ISSUE TITLE
GraalVM / TruffleRuby

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk#1014]
Now that 1.0 is out (https://blogs.oracle.com/developers/announcing-graalvm) started wandering, would TruffleRuby make any sense in embulk world?

**Comment by dmikurube** [comment]
I think "not specially". Embulk's core is going to be pure-Java anyways, and JRuby is already going to be optional there. It may happen that TruffleRuby gets to another "option", but it would never happen that TruffleRuby is in the "core".

**Comment by kakoni** [comment]
Makes sense. Personally I was interested as I've written few ruby based input/filter/output plugins and was thinking about performance under TruffleRuby (not sure if this would be easily done)
