### ISSUE TITLE
Java version detection in sh,bat

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1020]
I wrote Java version detection script in bash and Windows.

* [Win](https://github.com/hiroyuki-sato/java-version-test/blob/master/script.bat)
  * [AppVeyor](https://ci.appveyor.com/project/hiroyuki-sato/java-version-test/build/master%209) results.
* [Linux/Mac](https://gist.github.com/hiroyuki-sato/170ba4ea22a7920fe3b5b59d0b3776fb)

Ref: https://github.com/embulk/embulk/issues/976

**Comment by dmikurube** [comment]
Wow, thanks, @hiroyuki-sato!

I'll merge your PR if you implement the detection in `selfrun` scripts, or I'll implement it based on the code snippet of yours.
