### ISSUE TITLE
Bintray require TLS 1.2. but PowerShell doesn't use it by default.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1029]
Related #1028 

Lately, Bintray (embulk binary hosted site) must use TLS 1.2 protocol.
And PowerShell doesn't use it by default. (use TLS1.1)

This is the workaround until PowerShell will change the default with 1.2.

```
PowerShell -Command "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::TLS12; Invoke-WebRequest http://dl.embulk.org/embulk-latest.jar -OutFile embulk.bat}"
```

Ref1: [Add support for TLS 1.2 (Invoke-WebRequest, Invoke-RestMethod)](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/15150051-add-support-for-tls-1-2-invoke-webrequest-invoke)
Ref2: [Twitter](https://twitter.com/dmikurube/status/1019387999384027138) (Japanese text)

**Comment by hiroyuki-sato** [comment]
@dmikurube 
What do you think this [comment](https://twitter.com/mikoto2000/status/1058958733512855552)?
A user (beginner) wants to know the command which is written in #1030

**Comment by dmikurube** [comment]
@hiroyuki-sato Sorry that I've overlooked that. Commented in #1030.
