### ISSUE TITLE
add transform engine

### ISSUE THREAD

**Issue by cmdares** [embulk/embulk#1035]
e.g.
"transformer": [{
                "name": "dx_groovy",
                "parameter": {
                    "code": "Column column = record.getColumn(2);
                    String oriValue = column.asString();
                    def jsonSlurper = new JsonSlurper();
                    def object = jsonSlurper.parseText(oriValue);
                    boolean isWatched = object.isMatched;
                    long paidNum = 0;
                    long noPaidNum = 0;
                    def list = object.details;
                    list.each { 
                        boolean settlement = it.settlement;
                        if(settlement){
                            paidNum++;
                        }else{
                            noPaidNum++;
                        }
                    };
                    record.setColumn("field_ext1", new BoolColumn(isWatched));
                    record.setColumn("field_ext2", new LongColumn(paidNum)); 
                    record.setColumn("field_ext3", new LongColumn(noPaidNum));
                    return record;",
                    "extraPackage": ["import groovy.json.JsonSlurper;"]
                }
            }]

or

"transformer": [{
                "name": "dx_groovy",
                "script": "trans_add_column.groovy"     ----invoke groovy script.
            }]

**Comment by hiroyuki-sato** [comment]
Hello, @cmdares 

Some plugin supports scripting. You can create a plugin using other languages (e.g. Groovy)

Best regards.

Plugin  | Language
-----------------------------------------------------------------------------|-------
[embulk-filter-ruby_proc](https://rubygems.org/gems/embulk-filter-ruby_proc) | Ruby
[embulk-filter-script](https://rubygems.org/gems/embulk-filter-script) | Ruby
[embulk-filter-calcite](https://rubygems.org/gems/embulk-filter-calcite) | Apache Calcite(SQL)
[embulk-input-command](https://rubygems.org/gems/embulk-input-command) | sh, bat command
[embulk-filter-nashorn_test](https://github.com/hiroyuki-sato/embulk-filter-nashorn_test) | JavaScript(Nashorn) not released

**Comment by dmikurube** [comment]
@cmdares Thanks for your request. But it's totally about a plugin, not the Embulk core framework.

As @hiroyuki-sato mentioned, you may try some existing plugins with scripting, or you may develop a new plugin, by yourself.

Let me close this ticket.
