### ISSUE TITLE
[Feature Request] Snowflake support

### ISSUE THREAD

**Issue by kulmam92** [embulk/embulk#1036]
Do you have any plan to support Snowflake as input and output of embulk?

**Comment by hiroyuki-sato** [comment]
Hello, @kulmam92 

Have you ever tried embulk-input-jdbc with [Snowflake JDBC driver](https://docs.snowflake.net/manuals/user-guide/jdbc.html)?

If that plugin doesn't work as expected, Someone needs to develop a plugin for Snowflake.

**Comment by dmikurube** [comment]
@kulmam92 Thanks for your request. But it's totally about a plugin, not the Embulk core framework.

As @hiroyuki-sato mentioned, you may try [`embulk-input-jdbc`](https://github.com/embulk/embulk-input-jdbc) and [`embulk-output-jdbc`](https://github.com/embulk/embulk-output-jdbc) with the JDBC driver you see, or you may develop a new plugin, by yourself.

Let me close this ticket.

**Comment by kulmam92** [comment]
@dmikurube That's right. I need a plugin for Snowflake

@hiroyuki-sato 
To bring data into Snowflake I need to upload data to S3 and import data using copy into command like Redshift.
https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
I was thinking it would be nice to have a plugin like Redshift so that it can be done with single step.

**Comment by hiroyuki-sato** [comment]
Hello, @kulmam92 

I create new issue for developing 3rd party plugin which uses embulk-output-jdbc.jar .
https://github.com/embulk/embulk-output-jdbc/issues/237
