### ISSUE TITLE
latest download no longer available

### ISSUE THREAD

**Issue by rickrdvaughn** [embulk/embulk#1044]
The download instructions are not currently valid as https://dl.embulk.org/embulk-latest.jar is not available.  Is this planned?

**Comment by rickrdvaughn** [comment]
Actually I should revise this... latest does indeed point to https://dl.bintray.com/embulk/maven/embulk-0.9.8.jar which is not there.

**Comment by dmikurube** [comment]
@rickrdvaughn Sorry. Embulk v0.9.8 was released just yesterday. Library jars were uploaded successfully in Bintray, but the all-in-one exexutable embulk-0.9.8.jar was not uploaded there silently.

I manually uploaded that just now.
