### ISSUE TITLE
How to install plugins without internet ? 

### ISSUE THREAD

**Issue by SakirCiloglu** [embulk/embulk#1073]
Hi,

I downloaded plugins another machine using 'install gem list ....' .Since my other machine has no internet.

I put all folders under the /.embulk folder ( /lib folder)

But the error: Input Plugins 'oracle' is not found  

I try to check 'embulk gem list' bu i cant see plugins...

How can i install plugins without internet?

**Comment by dmikurube** [comment]
You may be able to use `gem install --local <gem file>`. Please look for `gem`'s manual for the details.

**Comment by SakirCiloglu** [comment]
Thanks.Problem solved with gem install  —local < gem file>
