### ISSUE TITLE
Your project embulk/embulk is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [embulk/embulk#1086]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  commons-cli commons-cli (embulk-core/build.gradle)
  version: 1.3.1

  Jira issues:
  Optional argument picking up next regular option as its argument
  affectsVersions:1.3.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-265?filter=allopenissues
  HelpFormatter#setOptionComparator(null) doesn't display the values in inserted order
  affectsVersions:1.3.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-266?filter=allopenissues

  2  org.slf4j slf4j-api (embulk-core/build.gradle)
  version: 1.7.12

  Jira issues:
  Initializing org.slf4j.helpers.Util fails if SecurityManager denies "createSecurityManager"
  affectsVersions:1.7.12
  https://jira.qos.ch/projects/SLF4J/issues/SLF4J-324?filter=allopenissues
  jul-to-slf4j inconsistent message format
  affectsVersions:1.7.12
  https://jira.qos.ch/projects/SLF4J/issues/SLF4J-337?filter=allopenissues

  3  ch.qos.logback logback-classic (embulk-core/build.gradle)
  version: 1.1.3

  Jira issues:
  release process fails with version 2.10.1 of maven-javadoc-plugin
  affectsVersions:1.1.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1062?filter=allopenissues
   JaninoEventEvaluatorTest and MDCBasedDiscriminatorTest fail under Linux
  affectsVersions:1.1.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1063?filter=allopenissues
  Unable to set string properties to json strings with nested nodes
  affectsVersions:1.1.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1101?filter=allopenissues
  ConsoleAppender does not report the correct ConsoleTarget values in case of problem
  affectsVersions:1.1.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1132?filter=allopenissues
  CharSequenceToRegexMapper#findMinMaxLengthsInSymbols() always returns min=0 
  affectsVersions:1.1.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-971?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by dmikurube** [comment]
Thanks for reporting. :) We're aware that we're using old libraries, but we have blockers against upgrading them, especially about compatibility with plugins.

We're already working to mitigate/eliminate the blockers.
