### ISSUE TITLE
[Feedbacks Wanted] JSON Parser plugin's enhancement

### ISSUE THREAD

**Issue by kamatama41** [embulk/embulk#1102]
## Overview

Current built-in JSON parser plugin has only one feature that it can parse multiple JSON documents to Embulk records that have just one Embulk JSON column. We'd like to enhance it with some new features.

## New features (draft)
- Selectable a specific value in JSON document as an Embulk column
```json
{"id": 1, "name": "Alice"}
{"id": 2, "name": "Bob"}
```
```yaml
in:
  type: ...
  parser:
    type: json
    columns:
      - {name: id, type: long}
      - {name: name, type: string}
```

```
+---------+-------------+
| id:long | name:string |
+---------+-------------+
|       1 |       Alice |
|       2 |         Bob |
+---------+-------------+
```

- Support pointing specific value via [JSON Pointer](https://tools.ietf.org/html/rfc6901) expression
```json
{ "result": {"id": 1, "name": "Alice"} }
```
For example, we can specify the nested JSON object as an Embulk record via a pointer `/result`
```
+-------------------------+
|             record:json |
+-------------------------+
| {"id":1,"name":"Alice"} |
+-------------------------+
```

- JSON array can be flattened to each Embulk record

```json
[
  {"id": 1, "name": "Alice"},
  {"id": 2, "name": "Bob"}
]
```

```
+-------------------------+
|             record:json |
+-------------------------+
| {"id":1,"name":"Alice"} |
|   {"id":2,"name":"Bob"} |
+-------------------------+
```

cc: @dmikurube , @sakama, @muga

**Comment by kamatama41** [comment]
Dear users of JSON parser plugin,
The features are experimentally released since Embulk 0.9.5. We would like your feedback to improve it, thank you!

**Comment by hiroyuki-sato** [comment]
@kamatama41 

I found the typo. Embulk 0.9.5 -> Embulk 0.9.15

I would like to know `bob`'s data in the first case.

It that the following?

```json
{"id": 1, "name": "Alice"},
{"id": 2, "name": "Bob"}
```

**Comment by kamatama41** [comment]
@hiroyuki-sato 
Thank you for pointing out, you are right. I fixed them.

**Comment by hiroyuki-sato** [comment]
@kamatama41 I recommend you post this feedback request to embulk-announce.

**Comment by dmikurube** [comment]
The enhancement has been landed for a long time. Let's close this feedback request.
