### ISSUE TITLE
Unsupport nested-JAR style JAR plugins

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#1110]
Currently, Embulk supports JAR-based Embulk plugins to load their dependencies in three ways.

1. Expand all dependencies flat into the plugin JAR
2. Embed all dependencies nested in the plugin JAR
3. Specify dependencies as Maven dependencies of the plugin artifact

1 is the most primitive way, but basically not recommended because the package easily gets bigger, and their license issues are not very clear.

2 was implemented around #792 to relax the problems of 1. Dependency JARs are embedded in the main plugin JAR as-is, and they're loaded by `org.embulk.plugin.PluginClassLoader`. But, the package is still big, and `PluginClassLoader` has gotten much complicated by this change.

3 is implemented the most recently in #1012 and #1015. Dependency libraries are not included in the main plugin JAR, but loaded through `<dependencies>` declarations in the plugin's `pom.xml`. To make the loaded versions clear, Embulk finds only the "direct" dependencies, without transitioned dependencies.

----

Maven-based JAR plugins are not very popular yet, and it should be safe to remove some features. Because we already have 3, and 2 is too complicated, let's remove the feature of 2.

**Comment by kamatama41** [comment]
Done.

**Comment by kamatama41** [comment]
Ah, It should be removed after new version is released.

**Comment by dmikurube** [comment]
v0.9.17 is out. Closing!
