### ISSUE TITLE
Where is release note?

### ISSUE THREAD

**Issue by sonots** [embulk/embulk#1113]
If I google `embulk release note`, this URL appears https://www.embulk.org/docs/release.html, but 404 Not Found.

![image](https://user-images.githubusercontent.com/2290461/53693666-158fdc00-3de7-11e9-8cdb-d1a36c8e9824.png)

**Comment by sonots** [comment]
Maybe, just moved to use https://github.com/embulk/embulk/releases?
It looks better to remove the release.html from google cache.

**Comment by dmikurube** [comment]
Yes, the release pages have been moved to Git annotated tags / GitHub Releases. The list page has been accidentally removed in #1092.

Getting it recovered by #1116.

**Comment by sonots** [comment]
Thanks!
