### ISSUE TITLE
embulk -R--help seems not working

### ISSUE THREAD

**Issue by sonots** [embulk/embulk#1114]
embulk --help tells

```
VM options:
...
   -R...                            Set JRuby options (use -R--help to see available options)
```

However, `embulk -R--help` does not show JRuby options.
I tried with the latest  0.9.15 and some old embulks such as 0.8.0.

**Comment by sonots** [comment]
Actually, I wanted to examine the version of bundled jruby as `embulk -R--version`, but it also did not work.

**Comment by dmikurube** [comment]
Thanks for reporting. Now `-R` has a limited usage as of #707, and since #962. Only `-R--dev` is working.

It's a problem of the help message. Fixing it in #1115.

**Comment by sonots** [comment]
Understood about current situation. Thanks.
