### ISSUE TITLE
Provide an official way to test Ruby-based plugins

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#1129]
Embulk has not released its `gem` versions since v0.9.0. It has caused some difficulties to test Ruby-based plugins.

We'll need to provide an official way to test Ruby-based plugins. Let's discuss it in this Issue.

**Comment by hiroyuki-sato** [comment]
Now I'm developing [`embulk-test`](https://github.com/hiroyuki-sato/embulk-test) gem for testing embulk ruby plugin. Please let me know if you have any comments.

In my plan, the plugin developer runs the following steps.

* Prepare JRuby in a development environment
* It must be the same version with built-in JRuby (I think embulk will separate JRuby in a future release)

* create embulk template

```
embulk new ruby-input foo
cd embulk-input-foo
```


A `gemspec` file (`embulk-input-foo.gemspec` in this case) contains the following entry.

```
  spec.add_development_dependency 'embulk-test', '~> 0.1'
```

 `Rakefile` contains the following entry for loading embulk task.

```
require 'embulk/test/embulk_test_tasks'
```


* Download embulk.jar into `vendor/embulk/embulk.jar` with the following commands

For latest 

```
bundle exec rake embulk:test:download_jar
```

For downloading specific version. 

```
bundle exec rake embulk:test:download_jar[0.9.15]
```
(I like `bundle exec rake embulk:test:download_jar 0.9.15`. but I don't know hot to do that)

Prepare step finish.

Let's test plugin.

[This document](https://qiita.com/sonots/items/13bae6db72a71a5f45b5#jruby-プラグインの単体テストを流す) (Japanese) is said that current implementation requires load `embulk.jar` before loading gems. So test command will be

```
bundle exec ruby -r ./embulk.jar -r embulk -r embulk/java/bootstrap -e test/test.rb
```

Or

```
$ bundle exec RUBYOPT="-r ./embulk.jar -r embulk -r embulk/java/bootstrap" rake test
```

This is better just execute `bundle exec rake test`

**Comment by hiroyuki-sato** [comment]
I'm creating a new ruby plugin template. 
I'll appreciate if you have any comment.

https://github.com/hiroyuki-sato/embulk/tree/split-ruby-test

This branch works well to `bundle exec rake embulk:test:download_jar` command.

Example output is below.

Before test, you need `rbenv` & `jruby-9.1.15.0` 

Create new ruby template

```
% embulk-0.9.18-SNAPSHOT.jar new ruby-input hoge
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
2019-04-09 20:54:48.618 +0900: Embulk v0.9.18-SNAPSHOT
Creating embulk-input-hoge/

Plugin template is successfully generated.
Next steps:

  $ cd embulk-input-hoge
  $ bundle install                            # install one using rbenv & rbenv-build
  $ bundle exec rake embulk:test:download_jar # download embulk.jar for testing
  $ bundle exec rake                          # build gem to be released
  $ bundle exec embulk run config.yml         # you can run plugin using this command
```

bundle install 

```
% cd embulk-input-hoge
% bundle install
fatal: not a git repository (or any of the parent directories): .git
The git source `git://github.com/hiroyuki-sato/embulk-test.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/hiroyuki-sato/embulk-test.git
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.2
Using bundler 2.0.1
Using embulk-input-hoge 0.1.0 from source at `.`
fatal: not a git repository (or any of the parent directories): .git
Using power_assert 1.1.4
Using test-unit 3.3.1
Using embulk-test 0.1.0 (java) from git://github.com/hiroyuki-sato/embulk-test.git (at master@0c73b08)
Bundle complete! 4 Gemfile dependencies, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
hsato-mbp13:embulk-input-hoge hsato$ bundle exec rake embulk:test:download_jar
fatal: not a git repository (or any of the parent directories): .git
Downloading https://dl.embulk.org/embulk-latest.jar ...Done
```

Download embulk.jar into `./vendor/embulk/embulk.jar`

```
% bundle exec rake embulk:test:download_jar
fatal: not a git repository (or any of the parent directories): .git
Downloading https://dl.embulk.org/embulk-latest.jar ...Done
```

**Comment by dmikurube** [comment]
We have no plans for expanding Ruby-based Embulk plugins. Closing this issue.
