### ISSUE TITLE
jffi1255460348143753573.dll and jruby-XXXXX folder in workspace directory

### ISSUE THREAD

**Issue by kulmam92** [embulk/embulk#1139]
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: windows 2016
  * Java version: JRE8
  * Embulk version: 0.9.16
  * Your Embulk configuration (YAML)
  * Plugin versions
* Write all what you did, e.g. your commands executed
* Write what you expected and observed actually

I'm running embulk using digdag.
When I checked the default workspace  location(C:\Users\embulk_svc\AppData\Local\Temp), there are a lot of files and folders that looked generated from embulk. It consumed more than 4G of disk space.

jffi12554603481XXXXXXXX.dll
jruby-XXXXX folder

Does anyone know why those are created and when those are deleted?

**Comment by dmikurube** [comment]
@kulmam92 Expected to be by: https://github.com/jruby/jruby/issues/3657

It does not look fixed yet on JRuby side. There's nothing we can help, unfortunately.

**Comment by kulmam92** [comment]
If that's the case, I will close this. I created a scheduled job that deletes those files regularly.
