### ISSUE TITLE
Improve TempSpace

### ISSUE THREAD

**Issue by tvhung83** [embulk/embulk#1151]
### Problems
* Temp space dir contains [space in name](https://github.com/embulk/embulk/blob/v0.9.17/embulk-core/src/main/java/org/embulk/spi/ExecSession.java#L101), eg. `2019-05-15 11:35:48.617 UTC`
* There is a rare issue of temp file not found > add more logs when embulk [clean up temp files](https://github.com/embulk/embulk/blob/fd9c0c0234033e40808478544ffcf8832e4b2aa0/embulk-core/src/main/java/org/embulk/exec/BulkLoader.java#L378)

### Expected result
* Rename temp space to not include space
* Add logs during clean up (but not too verbose)

**Comment by dmikurube** [comment]
To be fixed in v0.9.20 by #1190 and #1189... to be confirmed.

**Comment by dmikurube** [comment]
It looks to be done in Embulk v0.9.20. We no longer observe the "temp file not found" errors. Let me close it!
