### ISSUE TITLE
Potential resource leak in SelfContainedJarFile

### ISSUE THREAD

**Issue by shroman** [embulk/embulk#1184]
SelfContainedJarFile doesn't close `JarInputStream`.
https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/deps/SelfContainedJarFile.java#L60

This is a potential resource leak.

**Comment by dmikurube** [comment]
Ah... IIRC, its initial implementation was trying to read from `JarInputStream` on the fly, but changed the mind after considering pros and cons. It now reads all the contents in memory, then we can close it.

Thanks for the good catch. It's to be fixed.
