### ISSUE TITLE
How to check resume function for plugin

### ISSUE THREAD

**Issue by toanvan** [embulk/embulk#1187]
Dear all,
I have a question.
Currently I'm developing embulk. I implemented  resume function for my plugin but I can't confirm operation by test for resume function. How to test  resume function ? How to implement a transaction fail during run embulk to check resume function? 

Thank you!

**Comment by shroman** [comment]
Hi, if you need to trigger `resume`, I think you can create its configuration mock (see https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/EmbulkRunner.java#L284)

**Comment by toanvan** [comment]
thank you so much your comments,
Is there an easier method than that?

**Comment by hiroyuki-sato** [comment]
Hello, @toanvan.

#740 may help. Unfortunately, resume doesn't work for a long time.

**Comment by toanvan** [comment]
@hiroyuki-sato 
thank you,
