### ISSUE TITLE
oracle input parallel extraction

### ISSUE THREAD

**Issue by cmdares** [embulk/embulk#1191]
how to control the parallel for oracle ? 
eg. use raw function ora_hash()
so the sql like select *** from *** where 1=1 and ...   and ora_hash(rowid,8)=0,1,...8  9thread(parallel)
Is the the fastest way. Especially for full data extraction.
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hiroyuki-sato** [comment]
Hello, @cmdares 

Could you ask a plugin usage on [a plugin page](http://github.com/embulk/embulk-input-jdbc)?

embulk-input-jdbc (include Oracle) always use one task. Not parallelize now.

**Comment by dmikurube** [comment]
Unrelated to the Embulk core. Let's close it.
