### ISSUE TITLE
Embulk does not have a mascot or logo

### ISSUE THREAD

**Issue by repeatedly** [embulk/embulk#12]
This is an important issue!

**Comment by kiyokazu** [comment]
i think so too!!!!

**Comment by otaki-ryuta** [comment]
+1

**Comment by frsyuki** [comment]
Now, logo competition is open on 99designs!:
http://99d.me/c/9xz3

**Comment by frsyuki** [comment]
Here is the logo!!!!

![](https://gist.githubusercontent.com/frsyuki/5b79f70469c855fe4f07/raw/a1c80ca7f73d804236813f52377a539c6b2161d0/embulk-logo.png)

Orca bringing embulk.

Font: VAGRundschriftD
