### ISSUE TITLE
Add documents for built-in plugins

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#122]
There're no documents about built-in plugins.

* input-file
* output-file
* parser-csv
* formatter-csv
* decoder-gzip
* encoder-gzip
* output-stdout
* output-null

**Comment by hiroyuki-sato** [comment]
I wrote built-in plugin documentation. and Now I'm reviewing. 

And Maybe I need to convert sphinx format. 

Please comment. 
https://gist.github.com/hiroyuki-sato/cd936287c992e77e8970

**Comment by frsyuki** [comment]
Fixed at 67af5eea99c93389e753b9cb7dd23466c80afab6
