### ISSUE TITLE
Developers' Slack workspace

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#1222]
We have a Slack workspace for Embulk plugin developers to discuss and Q&A on `v0.10` issues. If you want to join, comment here with your email address, or any reference to your email.

(Note: The Slack workspace is for plugin **developers** not for **users**. We don't provide user support there.)

**Comment by kakoni** [comment]
Yes please.

**Comment by dmikurube** [comment]
@kakoni Thanks. I've sent an invitation to the e-mail address you use in your Git repositories. (If the address is not correct, please let me know.)

We use English and Japanese in the Slack workspace. Please don't hesitate to post in English although you may see several Japanese messages there as many of plugin developers are from Japan.

`v0_10` will be the channel to discuss v0.10 topics.

**Comment by u110** [comment]
Hello, please invite me to join the slack!

**Comment by dmikurube** [comment]
@u110 Hi, could you tell us what plugins you have maintained / contributed for?  As written in the issue description (and in the slides for the meetup you might have seen), the Slack workspace is for plugin developers.

**Comment by u110** [comment]
@dmikurube 
I have not yet been able to contribute to any of plugins,
but I'm interested in improving embulk-input-jdbc. (especially for oracle, mysql)

**Comment by dmikurube** [comment]
@u110 Sounds good! I'm going to send an invitation to the email address written on your `github.io` website.

**Comment by dmikurube** [comment]
@kakoni I thought I've sent an invitation to you, but the invitation still looks unaccepted. Please let me know if you see anything wrong.

**Comment by kakoni** [comment]
@dmikurube Got lost in my mailbox;) Just joined. Thank you for the invite.

**Comment by vikke** [comment]
invite me plz.

**Comment by dmikurube** [comment]
@vikke Could you tell us your email address to invite? I went into your GitHub account page, but I was no address available.

**Comment by vikke** [comment]
@dmikurube sorry, i updated my profile.

**Comment by dmikurube** [comment]
The Slack workspace has been deleted.

Instead, Zulip is available for developers around Embulk: https://embulk-dev.zulipchat.com/
