### ISSUE TITLE
Add an option to CSV parser plugin to skip a line if it starts with "#"

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#123]
Some CSV files have `#` character at the beginning of a line as a comment.
It would be great if guess-csv can guess it.

**Comment by repeatedly** [comment]
Maybe, adding option like skip_pattern is better.
CSV has no common view ;p

**Comment by frsyuki** [comment]
Help wanted:
If you have an example CSV file which needs this option or similar option, please comment here.

**Comment by randyh0329** [comment]
in our CSV format, we have `#CHECKSUM 972540854` as end of line.

I modified the CSV parser related function to support skip_pattern in configuration.
reference: https://goo.gl/jtcB8r

I know it's not the same idea as using guess-csv.
