### ISSUE TITLE
[feature request] Override GEM_HOME environment variable. (install a plugin into another place)

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1234]
## Desctription

I would like to override `GEM_HOME` configuration for testing the Embulk 0.10 series.
(I want to install embulk plugin into another place.)

@dmikurube suggest me to use [gem_home](https://github.com/embulk/embulk/blob/v0.10.0/docs/design/external_variables.md#gem_home) system config option. But embulk v0.10.0 can't use this option.

```
embulk-0.10.x gem install -Xgem_home=/tmp/hoge embulk-output-bigquery
2020-03-26 16:03:58.366 +0900: Embulk v0.10.0
Gem plugin path is: /Users/user/.embulk/lib/gems
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: -Xgem_home=/tmp/hoge
```

## Workaround

Use bundler a bit while.

## Reference

https://github.com/embulk/embulk/blob/v0.10.0/docs/design/external_variables.md#gem_home-and-gem_path

https://github.com/embulk/embulk/blob/v0.10.0/embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java#L692-L694

**Comment by dmikurube** [comment]
I didn't remember it's still a problem. Do you know?  @hiroyuki-sato

**Comment by hiroyuki-sato** [comment]
Let's close this issue.

embulk 0.10.0 did not recognize -X gem_home option.

```
embulk-0.10.0 -X gem_home=/tmp/gem gem install liquid
Embulk v0.10.0
...
error: Unknown subcommand gem_home=/tmp/gem.
```

The latest version supports `gem_home` options.

```
embulk-0.10.48-SNAPSHOT.jar -X gem_home=/tmp/gem gem install liquid

...
2023-04-12 00:02:42.388 +0900 [INFO] (main): Loaded JRuby runtime 9.3.6.0
2023-04-12 00:02:43.378 +0900 [INFO] (main): Environment variable "GEM_HOME" is not set. Setting "GEM_HOME" to "/tmp/gem" from Embulk system property "gem_home" for the "gem" command.
Fetching liquid-5.3.0.gem
Successfully installed liquid-5.3.0
Parsing documentation for liquid-5.3.0
Installing ri documentation for liquid-5.3.0
Done installing documentation for liquid after 5 seconds
1 gem installed
Exiting RubyGems with exit_code 0
```
