### ISSUE TITLE
Incompatible timestamp parser behavior if input data contains picoseconds.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1235]
Type: Bug Report
----------------------------------------------------------------------

* Write the following environmental information.
  * OS version: macOS 10.15.4
  * Java version: 1.8.0_192
  * Embulk version: See below

Reported by [@hito4t](https://github.com/embulk/embulk-output-jdbc/pull/269#issuecomment-604766508)

If input data contains picoseconds value like `2016-09-11 12:34:45.123456789012 +0000`
At least, 0.8.39 trim under milliseconds value. Embulk 0.8.18 doesn't trim milliseconds and microseconds.
**UPDATE** This behavior changed in embulk 0.8.27

I created to reproduce data.
https://github.com/hiroyuki-sato/embulk-support/tree/master/20200327_output-jdbc-timestamp

| data   | value(TIMESTAMP12_ITEM)                |
|--------|----------------------------------------|
| input  | 2016-09-11 12:34:45.123456789012 +0000 |
| 0.8.18 | 2016-09-11 12:34:45.123456 +0000       |
| 0.8.26 | 2016-09-11 12:34:45.123456 +0000       |
| 0.8.27 | 2016-09-11 12:34:45.000000 +0000       |
| 0.8.39 | 2016-09-11 12:34:45.000000 +0000       |
| 0.9.23 | 2016-09-11 12:34:45.000000 +0000       |

I'm not sure whether this issue need to fix or not.
I just want to share this issue.

**Comment by dmikurube** [comment]
Hmm, v0.8.27 indicates that #611 was the reason. Hmm, it's a long time ago... Let us consider we would fix it not won't fix.

**Comment by hiroyuki-sato** [comment]
I think this issue doesn't need to fix.

* This incompatible behavior is only value which has picoseconds.
* If input value has nanoseconds (ex. 2016-09-11 12:34:45.123456789), 0.9.23 and 0.8.18 worked the same (It output `2016-09-11 12:34:45.123456 +0000`) I'll add more test result later.
* It seems that picoseconds doesn't support on Ruby. (It seems that `strftime` doesn't support `%12N`)

@hito4t What do you think?

**Comment by hito4t** [comment]
@hiroyuki-sato 
I agree with you.
Thank you!

**Comment by hiroyuki-sato** [comment]
@hito4t Thank you! 
@dmikurube What do you think to set label `won't fix` and close issue?
