### ISSUE TITLE
db export performance benchmarks?

### ISSUE THREAD

**Issue by tooptoop4** [embulk/embulk#1243]
is there any timing on how long it takes to export 50GB from MySQL to CSV. Or 50GB from Oracle to CSV ?

**Comment by hiroyuki-sato** [comment]
Hello, @tooptoop4 

Do not post a plugin specific issue on this page.
I don't know any page about bulk-out performance.

**Comment by dmikurube** [comment]
@tooptoop4 As @hiroyuki-sato commented, this Issues is not for such questions. Also, IIUC, the performance would heavily depend on the machine, file system, MySQL, and Oracle. We have no any number that we can provide for you.

Thanks for your follow-up, @hiroyuki-sato.

Let us close this issue.
