### ISSUE TITLE
Embulk refers invalid schema?

### ISSUE THREAD

**Issue by llibra** [embulk/embulk#127]
I'm not sure, but it seems that Embulk holds schemas as output and input schema pairs into a list.

https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/spi/util/Filters.java#L45
```
out = plugins.get(pos).open(taskSources.get(pos), filterSchemas.get(pos), filterSchemas.get(pos + 1), out);
```

But the below code refers output schema only.

https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java#L97
```
public void run(final List<TaskSource> filterTasks, final List<Schema> filterSchemas)
{
    InputPlugin input = newInputPlugin(task);
    List<FilterPlugin> filterPlugins = newFilterPlugins(task);
    Schema filteredSchema = filterSchemas.get(filterSchemas.size() - 1);

    PageOutput out = new SamplingPageOutput(task.getSampleRows(), filteredSchema);
    try {
        out = Filters.open(filterPlugins, filterTasks, filterSchemas, out);
        input.run(inputTask, filteredSchema, 0, out);
    } finally {
        out.close();
    }
}
```

Is this a bug? Or I got it wrong?

**Comment by frsyuki** [comment]
Thank you for reporting. Fixed.

**Comment by llibra** [comment]
Thank you for your prompt response.
