### ISSUE TITLE
Issue while connecting to s3 bucket from Ec2

### ISSUE THREAD

**Issue by phaniari** [embulk/embulk#1283]
If your issue is not following the template, the maintainer may close the issue without notifications.

* Write the following environmental information.
  * OS version:linux
  * Java version: openjdk version "1.8.0_232"
  * Embulk version:Embulk v0.9.23
   * Plugin versions:embulk-output-s3-1.5.0
* Write all what you did, e.g. your commands executed:
i am trying to copy file from Ec2 to S3bucket.i am getting accessdenied error.
* Write what you expected and observed actually.
i need some help regarding configuration setup to connect to s3

**Comment by dmikurube** [comment]
We are not providing a user support here. Also, it looks like a problem in your `embulk-output-s3` configuration, not this `embulk` core project.

You may want to go: https://github.com/llibra/embulk-output-s3

Let us close this ticket.
