### ISSUE TITLE
ActiveSupport::HashWithIndifferentAccess-ish instead of Hash for Ruby plugin

### ISSUE THREAD

**Issue by nahi** [embulk/embulk#13]
It's developer friendly if plugins can access 'task' definition both via Symbol and String as a key.
```ruby
def self.transaction(config, &control)
  ...
  task[:foo] = 42
  yield(task, schema, threads)
  ...
  report
end

attr_reader :task
def run
  task[:foo] #=> nil because of ser-de, expecting 42
end
```

**Comment by frsyuki** [comment]
Very good but depending on ActiveSupport is too much...can we include only HashWithIndifferentAccess?

**Comment by aibou** [comment]
why don't you use https://github.com/intridea/hashie ?

**Comment by frsyuki** [comment]
@aibou what's the good points to use Hashie here?
