### ISSUE TITLE
`embulk gem/bundle` returns exit code = 0 when failed

### ISSUE THREAD

**Issue by NomadBlacky** [embulk/embulk#1364]
## Environment

* OS version: macOS Catalina 10.15.7
* Java version:
openjdk version "1.8.0_265"
OpenJDK Runtime Environment Corretto-8.265.01.1 (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM Corretto-8.265.01.1 (build 25.265-b01, mixed mode)
* Embulk version: 0.9.23

## Reproduction

```
$ embulk gem install embulk-input-mysql -v 9.9.9; echo $? # Unavailable version
2020-12-17 12:27:37.046 +0900: Embulk v0.9.23

Gem plugin path is: /Users/user/.embulk/lib/gems

ERROR:  Could not find a valid gem 'embulk-input-mysql' (= 9.9.9) in any repository
ERROR:  Possible alternatives: embulk-input-mysql
0
```

```
$ ls
Gemfile

$ cat Gemfile
source 'https://rubygems.org/'
gem 'embulk'
gem 'embulk-input-mysql', '= 9.9.9' # Unavailable version

$ embulk bundle; echo $?
2020-12-17 12:26:02.221 +0900: Embulk v0.9.23
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'embulk-input-mysql (= 9.9.9) java' in any of the gem sources
listed in your Gemfile.
0
```

## Expected

Returns exit code = 1

To check if there was a problem with the installation, need to check stderr etc.

**Comment by dmikurube** [comment]
Ah, got it.Thanks for filing the issue.

Although we won't release a fix for the current stable v0.9 series, we would try solving it in the development v0.10 series so that the next stable v0.11 will fix this issue.
