### ISSUE TITLE
Cache jar files to build JavaDoc and RDoc on Travis CI

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#138]
On Travis CI, downloaded dependent jar files are cached after `script` step before `after_success` step (see .travis.yml file). Thus jar files downloaded at `after_success` steps are not cached. `after_success` step downloads many large jar files including jruby-complete every time. This is inefficient.

A possible solution is to download the jar files at `script` step.

**Comment by dmikurube** [comment]
Travis CI has gone.
