### ISSUE TITLE
JRuby is not configured well to run "gem". Configure the Embulk system property "jruby".

### ISSUE THREAD

**Issue by adrianovieira** [embulk/embulk#1407]
What I have to do to install some plugins

If your issue is not following the template, the maintainer may close the issue without notifications.

Issue Type: Bug / Doubt Report
-----------------------

* Write the following environmental information.
  * OS version: fedora-32
  * Java version: openjdk version "1.8.0_282"
  * Embulk version; Embulk 0.10.27
  * Your Embulk configuration (YAML): What???
  * Plugin versions: trying to install some
* Write all what you did, e.g. your commands executed
    ```
    $ embulk gem install embulk-input-postgresql
    $ embulk gem install embulk-output-elasticsearch
    ```
* Write what you expected and observed actually

After both of those `embulk gem install..` I got this:
```
JRuby is not configured well to run "gem". Configure the Embulk system property "jruby".
```
How could I _configure the Embulk system property "jruby"_?

**Comment by dmikurube** [comment]
As written in https://www.embulk.org/, v0.10.* is unstable, development series. Not for your production use. Please use v0.9.23.

From v0.11 (next stable series), Embulk will not contain JRuby, and you'll have to specify a path to JRuby by `jruby=file:///your/jruby-complete-...jar`.

It will be documented when we release v0.11.
