### ISSUE TITLE
Test drivers or framework of plugins

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#151]
We want to write tests of plugins. For example, fluentd provides test framework (set of mocks) so that we can write tests easily for plugins.

**Comment by hito4t** [comment]
I've written tests for embulk-output-oracle plugin.
I hope they can be of some help.

https://github.com/hito4t/embulk-output-jdbc/tree/oracle-test/embulk-output-oracle/src/test/java/org/embulk/output/oracle

**Comment by dmikurube** [comment]
`embulk-junit4` (f.k.a. `embulk-test`) is there, and we plan to have a new `embulk-junit5` sooner. #1597
