### ISSUE TITLE
JRuby bridge for TimestampFormatter

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#157]
Embulk provides `org.embulk.spi.time.TimestampFormatter` so that plugins (especially formatter and output plugins) can format timestamps easily and users can use the consistent configuration parameter to configure timestamp formats.
However, it's difficult to use TimestampFormatter in JRuby-based plugins because there're no convenient bridges.

**Comment by dmikurube** [comment]
We have no plans for expanding Ruby-based Embulk plugins. Closing this issue.
