### ISSUE TITLE
embulk -X gem_home /path/to/foo (not gem_home=/pat/to/foo)

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1605]
Filed last year's discussion.

`-X key val` not `-X key=val` work unexpectedly.

```
java -jar /path/to/embulk/embulk-0.10.35.jar \
  -X embulk_home=/tmp/embulk_with_equal \
```

https://gist.github.com/hiroyuki-sato/49374af77dcc8877b4661893530af434

https://twitter.com/dmikurube/status/1517312140864294912?s=20

**Comment by dmikurube** [comment]
I could come from Apache Commons CLI's behavior.

We cannot "fix" it if so, but, we'll use `-X key=value` in our all public documents.

`-X key value` may work, but we basically do not expect it, and it's not our official recommendations.

Does this work for you?

**Comment by hiroyuki-sato** [comment]
Thank you for your comment. That policy looks good for me.
