### ISSUE TITLE
mark 0.10.x releases as pre-release??

### ISSUE THREAD

**Issue by chenrui333** [embulk/embulk#1613]
👋 according to [this post](https://www.embulk.org/articles/2020/03/13/embulk-v0.10.html), 0.10.x should be development releases, right? If that is the case, maybe you should consider marking all the 0.10.x releases as `pre-release`. Thanks!

also relates to https://github.com/Homebrew/homebrew-core/pull/128555

**Comment by dmikurube** [comment]
Maybe, but it's our decision. Thanks for your suggestion.
