### ISSUE TITLE
Performance and error handling in embulk

### ISSUE THREAD

**Issue by vinpokale** [embulk/embulk#163]
Hi,
I read the documentation of embulk but I could not find information related to performance.
I would like to know the performance(data loading speed) of embulk and how embulk handles the error.

Regards,
Vinayak

**Comment by frsyuki** [comment]
Here is a performance benchmark by @hito4t: https://translate.google.com/translate?sl=ja&tl=en&u=http%3A%2F%2Fhito4-t.hatenablog.com%2Fentry%2F2015%2F03%2F04%2F122051
He achieved a lot of improvement after that such as: https://translate.google.com/translate?hl=&sl=ja&tl=en&u=http%3A%2F%2Fhito4-t.hatenablog.com%2Fentry%2F2015%2F04%2F07%2F215837&sandbox=1

Error handling is discussed on #27.
