### ISSUE TITLE
Request for a new feature: replace sun.misc.Unsafe with Foreign Function and Memory API

### ISSUE THREAD

**Issue by RuixiangJiang** [embulk/embulk#1679]
Greetings!

Issue Type: New Feature Request
--------------------------------

* Write your concrete practical scenarios with the new feature you want.
Noticing that `embulk-core/src/main/java/org/embulk/exec/Slice.java` invokes sun.misc.Unsafe to do off-heap operations on a byte array named `this.base`, I have used a new API named Foreign Function and Memory (short for FFM, published in Java 22) to replace the unsafe codes in `Slice.java`.
* Write your expectation how your suggestion helps others as well.
This replacement doesn't affect the performance much, as it makes the whole project safer.

My replacement is based on Release 0.11.4, in which the command `gradle clean && gradle test` shows the release-version project can pass 194/207 tests. My replacement codes can also pass 194/207 tests. Note that my replacement needs Java version 22.
I hope it will be helpful, and I apologize for any inconvenience.

**Comment by dmikurube** [comment]
We are aware of the `sun.misc.Unsafe` issue, of course, but we're still around Java 8, unfortunately. We have a plan about migrating to modern Java, and the `sun.misc.Unsafe` migration would be performed alnog with the modern Java migration.

https://github.com/embulk/embulk/blob/main/docs/eeps/eep-0011.md

You may want to read through our EEPs if you're interested in the Embulk core framework.

https://github.com/embulk/embulk/tree/main/docs/eeps

**Comment by RuixiangJiang** [comment]
Thanks for your response! If Embulk would be around Java 22 in the future, I'll be more than delighted to create a Pull Request for my replacement of Unsafe codes.
