### ISSUE TITLE
Proposal: escape, quote and other options for CSV formatter plugin

### ISSUE THREAD

**Issue by sakama** [embulk/embulk#168]
Hi, I heard that built-in CSV formatter plugin doesn't support escape and quote now.
If you have no plan to do, I'm thinkng about writing it and send pull request.

Because I need CSV formatter for local-file output or load into Google BigQuery (need CSV or JSON). 
I'm author of [embulk-input-gcs](https://github.com/sakama/embulk-input-gcs) and [embulk-output-bigquery](https://github.com/sakama/embulk-output-bigquery) plugins.

How do you think about following specs?

## Options already exists

http://www.embulk.org/docs/built-in.html#csv-formatter-plugin

* `delimiter` string Delimiter character such as `,` for CSV, `\t` for TSV, `|` or any single-byte character	, by default
* `header_line` boolean If true, write the header line with column name at the first line
* `newline` enum Newline character (CRLF, LF or CR)	CRLF by default
* `charset` enum Character encoding (eg. ISO-8859-1, UTF-8)	UTF-8 by default

## Options I think need to implement

* `quote` string any-single-byte-character used to quote fields containing special characters. `"` by default
* `quote_policy` enum (ALL, MINIMAL, NONNUMERIC or NONE) `MINIMAL` by default
  * https://docs.python.org/3.4/library/csv.html#csv.QUOTE_ALL
  * `ALL` quote all fields
  * `MINIMAL`  only quote those fields which contain special characters such as **delimiter**, **quote** or any of the characters in lineterminator
  * `NONNUMERIC` quote all non-numeric fields
  * `NONE` never quote fields.  When the current delimiter occurs in value it is preceded by the current escape character. If escape is not set, skip line and output log like CSV parser.
* `escape` string escape character to escape a special character. `\\` by default
* `newline_in_field` enum Newline character in the field. (CRLF, LF, CR). LF by default
* `skip_empty_lines` boolean skip empty lines. `false` by default

### not support

I think it's better to control for each columns using filter plugins.

* trim
* null_string
* padding

## Reference

* [CSV File Reading and Writing — Python 3.4.3 documentation](https://docs.python.org/3.4/library/csv.html)
* [pandas.DataFrame.to_csv — pandas 0.16.0 documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html)
* [CSV Library Features Matrix - OrangeSignal CSV](https://translate.google.co.jp/translate?hl=ja&sl=ja&tl=en&u=http%3A%2F%2Forangesignal.github.io%2Forangesignal-csv%2Fcsv_library_feature_matrix.html)

**Comment by frsyuki** [comment]
Very good start point.

> delimiter, quote, escape, header_line, charset, newline

No-brainer. They're necessary.

> quote_policy

Well designed. Sounds good.

> newline_in_field

I don't have good ideas whether LF is good for default or not. But It's good start anyways.

> skip_empty_lines

How does this work? (what does "empty lines" mean?)

As you mention, null_string is tricky because if null_string is "" (empty string, which will be the default value, probably), actual empty string needs to be quoted even if quote_policy is MINIMAL.

**Comment by sakama** [comment]
Thanks for comment.

> I don't have good ideas whether LF is good for default or not. But It's good start anyways.

I'm also wondering LF is best or not.

CSV format written by MS Excel for Windows seems standard.

* newline: CRLF
* newline in field: LF (Alt+Enter input)


> How does this work? (what does "empty lines" mean?)

This means if all column in current-line is empty, CSV formatter doesn't output current-line.
But I'm wondering this option is really need or not.

> actual empty string needs to be quoted even if quote_policy is MINIMAL

I think if quote_policy is MINIMAL, empty string doesn't need to be quoted.
MS Excel for Windows seems same.

```python
#coding:utf-8
import csv

writer = csv.writer(open('test.csv', 'wb'), delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

writer.writerow(['ABC', '', 'DE,F', 'GH"I'])
```

result is...

```
ABC,,"DE,F","GH""I"
```

**Comment by hiroyuki-sato** [comment]
Thank you for your good working.

I checked `newline` and `newline_in_field` characters  on OSX Platform. 
I wrote CSV from MS-Excel file.

result 
* newline: CR
* newline_in_field: CR

[Test data](https://gist.github.com/hiroyuki-sato/0162f63fdbe09ca9d1bc)

**Comment by frsyuki** [comment]
@sakama

> actual empty string needs to be quoted even if quote_policy is MINIMAL

this is if null_string is "" (empty string)

**Comment by sakama** [comment]
Although I'm not fully able to understand that your comment.
Anyway I think it's better that CSV formatter plugin will not support null_string option.

**Comment by frsyuki** [comment]
I welcome pull-requests :+1:

**Comment by sakama** [comment]
Thanks! Maybe I can send pull-request within a week.
