### ISSUE TITLE
the site still points to 0.11.4 as the latest release

### ISSUE THREAD

**Issue by chenrui333** [embulk/embulk#1689]
Issue Type: Bug Report
-----------------------

Looks like the site still points to 0.11.4, raise this as bug in here. 

relates to https://github.com/Homebrew/homebrew-core/pull/194723

![image](https://github.com/user-attachments/assets/eb0d7a5c-4315-435d-86ae-49e6df76479f)

**Comment by hiroyuki-sato** [comment]
Hello, @chenrui333 
We don't maintain a Homebrew package. You can download the jar file from [the official site](https://github.com/embulk/embulk/releases).

**Comment by hiroyuki-sato** [comment]
@chenrui333 Ah, Sorry you are right. We need updates the version. I'll fix it.
