### ISSUE TITLE
Implementing sar binary decoder

### ISSUE THREAD

**Issue by ysksuzuki** [embulk/embulk#194]
Hello

I want to implement a sar binary file decoder which converts sar binary into json format with sadf command. After that, it is converted into csv and passed to the csv parser.
It requires the entire file to be converted into JSON at once during guess. For this, the sample buffer provided during guess is insufficient.(Only 30K)
Any idea?

```
cpu-load-all.1.cpu.full,network.net-nfs.getatt,cpu-load-all.2.iowait,network.net-sock.tcpsck,power-management.cpu-weighted-frequency.3.number,cpu-load-all.1.cpu ...
0,181,1.98,74,0,0 ...
```

**Comment by ysksuzuki** [comment]
I noticed that it's wrong to write a decoder plugin in this situation. I'll try to extend LocalFileInputPlugin.
Thanks.

**Comment by hiroyuki-sato** [comment]
Hello 

_I think_ you can also use ParserPlugin. 

For example.

* [embulk-parser-pcapng](https://rubygems.org/gems/embulk-parser-pcapng)
* [embulk-parser-roo-excel](https://rubygems.org/gems/embulk-parser-roo-excel)

I'll comment later about guess.
