### ISSUE TITLE
Develop a gradle plugin to make it easy for users to develop embulk plugins

### ISSUE THREAD

**Issue by nahi** [embulk/embulk#20]
Java developers probably don't want to write Ruby code and don't know Ruby's packaging system.
But Embulk uses RubyGems for packaging.

Idea here is that Embulk provides a gradle plugin to automate the packaging.

The plugin does:

* provide a task to create pkg/embulk-plugin-xyz.gem package.
  * the task builds a jar file and copies dependency jars to classpath/*
  * then package them into pkg/embulk-plugin-xyz.gem
  * I think it can assume that developers write embulk-plugin-xyz.gemspec file
* provide a task to release the gem file to RubyGems
  * I think it can assume that developers write ~/.gem/credentials file
* manage versions of dependencies of basic packages to not cause version conflicts with embulk-core (like parent pom file)

See also: #28

**Comment by frsyuki** [comment]
I think this becomes unnecessary by #160.
