### ISSUE TITLE
Failed to guess integer column with extra space

### ISSUE THREAD

**Issue by yyamano** [embulk/embulk#201]
embulk guess can't handle integer column with extra space correctly.

I know basically space should be considered part of a column, but some programs like MS Excel creates such a csv file.

http://www.mrexcel.com/forum/excel-questions/4143-csv-space-problem-resolved.html
http://tburette.github.io/blog/2014/05/25/so-you-want-to-write-your-own-CSV-code/
http://q.hatena.ne.jp/1355281826 (Japanese)

I'm not so sure if embulk should support it. What do you think?

```
% cat sample.csv 
0,DEF,123 ,567 ,90
1,DEF,123 ,567 ,90
2,DEF,123 ,567 ,90
3,ABC,1234,5678,90
4,DEF,123 ,567 ,90
5,DEF,123 ,567 ,90
% embulk guess guess.yml
2015-06-19 01:53:52.364 +0000: Embulk v0.6.11
2015-06-19 01:53:53.906 +0000 [INFO] (guess): Listing local files at directory '/tmp/t' filtering filename by prefix 'sample'
2015-06-19 01:53:53.914 +0000 [INFO] (guess): Loading files [/tmp/t/sample.csv]
in:
  type: file
  path_prefix: /tmp/t/sample
  parser:
    charset: ISO-8859-9
    newline: CRLF
    type: csv
    delimiter: ','
    quote: ''
    escape: ''
    skip_header_lines: 0
    comment_line_marker: null
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: c0, type: long}
    - {name: c1, type: string}
    - {name: c2, type: string}
    - {name: c3, type: string}
    - {name: c4, type: long}
exec: {}
out: {type: stdout}

Use -o PATH option to write the guessed config file to a file.
```

**Comment by frsyuki** [comment]
oh, what's a stupid Excel... Could you try this?:

1. add `trim_if_not_quoted: true` to `parser` config
2. run guess

If it works, I think embulk can run guessing with both of `try_if_not_quoted: true` and `try_if_not_quoted: false` and then take appropriate config.

**Comment by yyamano** [comment]
It works fine to me.
