### ISSUE TITLE
Implement JRuby bridge for FileInputPlugin

### ISSUE THREAD

**Issue by nahi** [embulk/embulk#21]
More Ruby plugsin!

**Comment by frsyuki** [comment]
lib/embulk/file_input_plugin.rb needs to implement `self.new_java` method. Implementation will be similar to `Embulk::InputPlugin.new_java` or `Embulk::ParserPlugin.new_java`. `Embulk::FileInputPlugin::JavaAdapter` needs to implement `transaction(java_config, java_control)`, `resume(java_task_source, task_count, java_control)`, `cleanup(java_task_source, task_count, java_commit_reports)`, and a method and/or class for `open`.

**Comment by dmikurube** [comment]
We have no plans for expanding Ruby-based Embulk plugins. Closing this issue.
