### ISSUE TITLE
Is there any way to pass Java system property?

### ISSUE THREAD

**Issue by ssmi1975** [embulk/embulk#226]
I tried to use jdbc output plugin (https://github.com/embulk/embulk-output-jdbc) with embedded derby, which is controlled by system properties. http://db.apache.org/derby/docs/10.5/ref/crefproper22250.html

Currently embulk seems to have an option to pass classpath, which is nice, but is there any way to pass system properties to Java process?

**Comment by frsyuki** [comment]
with command line, you can use `-J-Dkey=value`:

```
$ embulk -J-Dmy.prop.key=value run config.yml
```

**Comment by ssmi1975** [comment]
Thank you! Let me try.
