### ISSUE TITLE
Schema.builder API for Ruby

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#228]
I added spi.Schema.Builder to Java plugin API.
I want similar API for Ruby so that we can avoid this kind of code: https://github.com/treasure-data/embulk-parser-query_string/blob/7aec718f5f056301d23ac054c1c3cf3e8b7d7469/lib/embulk/parser/query_string.rb#L15-L22

**Comment by dmikurube** [comment]
We have no plans for expanding Ruby-based Embulk plugins. Closing this issue.
