### ISSUE TITLE
Resuming failed transaction

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#25]
A bulk load likely fails when we import large amount of data (say 1TB). When it fails, Embulk currently requires plugins to rollback entire transaction so that we can retry.
However, retrying the entire bulk load of the large data takes too long time. It's very good if we can resume the failed transaction from partially succeeded state.

Difficulties:

* What's the API for plugins?
* Is a input plugin responsible to skip tasks? Or, is a output plugin responsible to skip records?

**Comment by xerial** [comment]
This feature would be nested transaction, with which we can partially roll back sub tasks.

**Comment by frsyuki** [comment]
@xerial What do you mean nested transaction? Could you explain with an example scenario?

**Comment by frsyuki** [comment]
I'm writing some code at https://github.com/embulk/embulk/tree/resume branch.

**Comment by frsyuki** [comment]
#50 implemented this feature.
