### ISSUE TITLE
Fix confusing name of CommitReport

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#261]
CommitReport is a class used to return values from `run` to `transaction` (InputPlugin) or `open` to `transaction` (OutputPlugin). However, its name is confusing because `run` or `open` don't commit the transaction. Instead, `transaction` method commits transaction. `run` or `open` commits transaction partially and reports the results to `transaction` method.

So, to avoid the confusion, the name should be improved. Candidates are:

* RunReport
* PartialCommitReport

Migration idea is:

* Create a new class
* CommitReport extends it
* Change plugin interfaces and plugin template generator to use the new class. Existent plugins still work because CommitReport extends the new class.
* Add `@Deprecated` annotation to CommitReport

**Comment by muga** [comment]
the renaming and migration idea looks good to me.
