### ISSUE TITLE
Allow "selfupdate" to specify specific version

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#270]
`embulk selfupdate` command gets the latest version.
When the latest version caused a problem, I want to revert back to old version.
In this scenario, `embulk selfupdate <version>` is very good to have.

**Comment by cosmo0920** [comment]
I try to implement this feature this branch: https://github.com/cosmo0920/embulk/tree/specific-version-selfupdate.
But this branch will be conflict for selfupdate subcommand fix.
After selfupdate subcommand fix at master, I will create PR with this branch.

**Comment by frsyuki** [comment]
I've merged selfupdate fix.

* https://github.com/embulk/embulk/compare/master...cosmo0920:specific-version-selfupdate#diff-dcb0e3c8126ddf8d77d7de608e44e48aR257
** why don't you include `:version` in `options`?
* https://github.com/embulk/embulk/compare/master...cosmo0920:specific-version-selfupdate#diff-0f4dfcf1becb38c679f5f5e979faadc7R86
* https://github.com/embulk/embulk/compare/master...cosmo0920:specific-version-selfupdate#diff-0f4dfcf1becb38c679f5f5e979faadc7R86
** 404 Not Found is expected error because user can specify version which doesn't exist. So, how about saying "Specified version does not exist. See https://github.com/embulk/embulk/tree/master/embulk-docs/src/release for released versions" if status is 404?

**Comment by cosmo0920** [comment]
> * master...cosmo0920:specific-version-selfupdate#diff-dcb0e3c8126ddf8d77d7de608e44e48aR257
>   * why don't you include `:version` in `options`?

Ah! I didn't notice about it.  

> * master...cosmo0920:specific-version-selfupdate#diff-0f4dfcf1becb38c679f5f5e979faadc7R86
>   * 404 Not Found is expected error because user can specify version which doesn't exist. So, how about saying "Specified version does not exist. See https://github.com/embulk/embulk/tree/master/embulk-docs/src/release for released versions" if status is 404?

I see. I think that above exception message is better.
