### ISSUE TITLE
Plugin loader of Java plugins

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#28]
Embulk can't load java-based plugins (jar files) dynamically. Users need to add the jar files to classpath. Inconvenient...

**Comment by frsyuki** [comment]
An idea of the API design:

* a) Java-based plugins include jar files at classpath/* directory
* b) Even java-based plugins include lib/embulk/input_xyz.rb (or output_xyz.rb) file. Its code is as like this:
```ruby
loader = Embulk::PluginBuilder::PluginClassLoader.new(File.dirname(__FILE__)+"../../../classpath")
Plugin.register_output("csv", loader.get("org.embulk.output.CsvOutput.class"))
```

PluginClassLoader loads a class if it's found at the parent class loader. Otherwise, it loads the class from itself. This is how [JRubyClassLoader](http://jruby.org/apidocs/org/jruby/util/JRubyClassLoader.html) works to not cause phantom definition. (In other words, we might be able to use JRubyClassLoader).

**Comment by frsyuki** [comment]
#56 implemented java plugin loader.

**Comment by muga** [comment]
Great Job! I wanted the feature!
