### ISSUE TITLE
Parallel execution?

### ISSUE THREAD

**Issue by daledude** [embulk/embulk#301]
There is mention of parallel execution and a exec: but I don't see any docs for it. I'm interested in running the redshift output in parallel. How would I go about doing that?

**Comment by tasuku-s** [comment]
I guess when you use a input plugin with mention of parallel, such as embulk-input-filesplit plugin, output will becomes parallel.

**Comment by frsyuki** [comment]
I created a document for internal architecture. Is this document good enough to understand?
Please give me feedback:
http://www.slideshare.net/frsyuki/embuk-internals

**Comment by frsyuki** [comment]
Related: https://github.com/embulk/embulk/issues/232

**Comment by daledude** [comment]
That doc is interesting but it's for developers. From a user perspective there aren't any docs about the "exec" usage anywhere. Other than a mention that it merely exists in filter docs. Probably because it's specific only to the fileinput. 

Being that the word "parallel" was front and center in the projects description I expected more. You probably haven't had a need for implementing actual parallelism, yet. I was hoping to replace my custom Elasticsearch loader with embulk because it has a decent Redshift output and is easy to configure. Without being able to run X number of outputs, however, the process is very slow. I'm going to keep an eye on #232 with great interest.

Thanks for a useful project!

**Comment by frsyuki** [comment]
@daledude some input plugins don't support parallelizm depending on its data source. if you're using file input plugin, you can use embulk-input-filesplit plugin to get more parallelizm: https://github.com/hito4t/embulk-input-filesplit
