### ISSUE TITLE
Adding JSON type

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#306]
Case 1:  Many data sources provide schema-less data. Some data storages can accept schema-less data. In this case, current Embulk looses some information.

Case 2: When we want to load data from schema-less storage to schemaful data storage, we need to convert records. This conversion should be customizable. However, it is hard to implement fully-customizable conversion mechanism to all schema-less input plugins. It should be done by filter plugins. If input plugins produce a JSON column, and filter plugins flatten the JSON column into schemaful columns.

Case 3: Error handlers (https://github.com/embulk/embulk/pull/293#issuecomment-140296147)

Implementation:

Add JsonType class. Representation in Java may be org.msgpack.Value. Format in Page will be Value (references of `Value.immutableValue()` like Page.stringReferences) or serialized msgpack.

**Comment by muga** [comment]
I close this ticket because it was already supported in v08. Please reopen it if you still have tasks on it.
