### ISSUE TITLE
"Embulk  -J-D"  option on Windows environment.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#315]
Embulk support Java System property setting with ``-J`` option.
However It's not work properly on Windows environment. (not implement yet.)
It has workaround.

This option is useful for connect Google BigQuery with embulk-ouptut-bigquery plugin via proxy server.
See also 

## Windows

```
% embulk.bat -J-Dhttp.proxyHost="localhost" run test.yml
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
2015-09-30 19:13:23.580 +0900: Embulk v0.7.4
Embulk v0.7.4
usage: <command> [--options]
...

error: Unknown subcommand "localhost".
```

## Workaround

Use ``java`` command 

```
java -Dhttps.proxyHost="localhost" -Dhttps.proxyPort="8090" -jar embulk.bat test.yml
```

## Sample embulk oputput on OSX environment.

```
embulk -J-Dhttp.proxyHost="localhost" run test.yml
2015-09-30 19:16:05.701 +0900: Embulk v0.7.4
2015-09-30 19:16:08.574 +0900 [INFO] (transaction): Loaded plugin embulk-input-s3 (0.2.2)
...
```

## See also 

[Access Google BigQuery via proxy](http://qiita.com/hiroysato/items/cf3f6280b4803f250409) Japanese text

**Comment by hito4t** [comment]
It seems that DOS `for` splits the parameter such as `A=B` into `A` and `B`.

Unfortunately I don't know how to implement the batch without `for`.
(In addition, the batch doesn't work for some reason when trying to `goto` ahead. It works if the batch is not embedded in JAR.)

You can avoid that by enclosing the parameter by double quotations such as `"A=B"`. 
Can you try `"-J-Dhttp.proxyHost=localhost"`?

**Comment by hiroyuki-sato** [comment]
@hito4t Thank you for your advice.

It worked well with quote like the following.

```
embulk.bat "-J-Dhttps.proxyHost=xxxx” "-J-Dhttps.proxyPort=xxxx" run config.yml
```
