### ISSUE TITLE
Exit code always 0 in Cygwin

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk#325]
When an exception is thrown in Embulk, exit code is 1.
But when executing Embulk in Cygwin, exit code is always 0.

If selfrun.sh is modified as follows, correct exit code will be returned.
<pre>
java %java_args% -jar %this% %jruby_args% %args%

endlocal

exit /b
</pre>
↓
<pre>
java %java_args% -jar %this% %jruby_args% %args%

endlocal

exit /b %ERRORLEVEL%
</pre>

**Comment by cosmo0920** [comment]
It seems that similar patch has been merged master: https://github.com/embulk/embulk/pull/324
But it is not released yet.
Current master behaviour is your expected?

**Comment by hito4t** [comment]
Thank you for pointing it out!
I'll close this issue.
