### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by tcssrini** [embulk/embulk#344]
Whether Embulk supports encryption of files before sending it through SFTP .

I have one more issue , multiple threads are created if I use filesplit type . But for filesplit we have to give the exact file names . Our requirement is to do the file split for all the files in a directory .

Thanks
Srini

**Comment by cosmo0920** [comment]
> I have one more issue

I think you should split this issue.
One issue should treats one bug or feature request.

**Comment by cosmo0920** [comment]
And Could you write more concrete issue title?
Developers will be confused by abstract or only one word issue title.
And it makes hard to find similar issue....  :confounded:

**Comment by hiroyuki-sato** [comment]
Hello

* You can encrypt data at EncoderPlugin stage. 
* There are no plugin for encryption yet.
* So if you want to encrypt data, you need develop encoder plugin for encryption. 

Plese check following information.

* [Plugin Architecture](http://www.slideshare.net/frsyuki/embuk-making-data-integration-works-relaxed/26)
* [Encoder plugin list](http://www.embulk.org/plugins/#file-encoder)

**Comment by frsyuki** [comment]
#232 will improve parallelism even when number of input files is smaller than number of CPU cores.

**Comment by frsyuki** [comment]
@tcssrini what kind of encryption do you expect? Pre-shared key encryption such as DES3 or AES? Or public-key encryption such as PGP or RSA?

**Comment by tcssrini** [comment]
@frsyuki  Thanks for your reply . We are expecting AES .

**Comment by hiroyuki-sato** [comment]
FYI, 

Currently,  there are two encryption plugins.
* [embulk-encoder-encrypted_zip](https://rubygems.org/gems/embulk-encoder-encrypted_zip)
* [embulk-encoder-pgp_encryption](https://rubygems.org/gems/embulk-encoder-pgp_encryption)

**Comment by frsyuki** [comment]
I wrote embulk-filter-encrypt. You can encrypt column values.
https://github.com/embulk/embulk-filter-encrypt

Please reopen if it's not something you expected.
