### ISSUE TITLE
How to improve embulk-input-filesplit performance

### ISSUE THREAD

**Issue by benbenja** [embulk/embulk#350]
Hi,

         We have lots of 100 GB files in a directory. We need to basically read those files line by line and mask couple of columns using hash function and write it to another file. For following configuration it takes 9 hrs 10 mins to process single 100 GB file (1360,000,000 rows). Our hardware configuration 8 core, 65 GB RAM and 1 TB hard disk. Is there is any way to improve the performance?

in:
  type: filesplit
  path: {{ env.input_fpath }}
  header_line: true
  tasks: 24
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 0
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: timestamp, type: string}
    - {name: src_ip, type: string}
    - {name: src_port, type: long}
    - {name: dest_ip, type: string}
    - {name: dest_port, type: long}
    - {name: user_id, type: string}
    - {name: in_bytes, type: long}
    - {name: out_bytes, type: long}
filters:
  - type: hash
    columns:
    - {name: src_ip, algorithm: SHA-512}
    - {name: user_id, algorithm: SHA-512}
out:
  type: file
  path_prefix: {{ env.output_dpath }}/{{ env.fname }}_
  sequence_format: '%03d.'
  file_ext: csv
  formatter: {type: csv}

Thanks,
Ben

**Comment by hito4t** [comment]
Hi
You can use embulk-executor-mapreduce plugin and run embulk on hadoop.
It may improve performance.

**Comment by benbenja** [comment]
Hi,

         Thanks for your reply. Getting hadoop cluster may not possible in our user case. Just want to under is there any improvements that could made to the configuration to improve the current embulk-input-filesplit performance.

Thanks,
Ben

**Comment by hito4t** [comment]
Hi

It will not take so much time to input or output file.
I suppose that the bottleneck is calculating hash.
(I extracted the method for calculating hash from embulk-filter-hash plugin and executed in my machine. It took about 7 seconds to calculate hash for 100,000 items. Namely, about 53 hours for 2 items of 1,360,000,000 rows.)

How much is CPU usage? If it is almost 100%, and cannot change the hardware, the way to improve performance would be change the hash algorithm.

Thanks

**Comment by hiroyuki-sato** [comment]
Hi

This is example. 
MD5 faster than SHA-512. (1.6x)
SHA-1 too.
It is good idea to change hash algorithm. 

this is my test configuration. 

```
in: 
  type: file
  path_prefix: /path/to/file
  parser: 
    type: none
    message_key: message
filters:
  - type: hash
    columns: 
#      - { name: message, algorithm: SHA-512 }
      - { name: message, algorithm: MD5 }
out:
  type: "null"
```

Thanks.

**Comment by benbenja** [comment]
Thanks for the suggestion. Will try the same.

Regards,
Ben

**Comment by frsyuki** [comment]
embulk v0.8.0 will have #355 which improves performance on multicore CPUs.
