### ISSUE TITLE
Adding no-parse mode (copying files without parsing)

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#351]
In some cases, we want to copy files without parsing their contents. Embulk can be useful even for those cases because embulk supports plugin architecture.

This mode might be implemented using special parser (and formatter) plugins, or an special option to executor plugins. Expected results of this mode is better performance and ease of configuration.

**Comment by hiroyuki-sato** [comment]
👍

I know two cases.
They want to use embulk as copy tool.

* [Twitter](https://twitter.com/ReSTARTR/status/670917464918654976) (Japanese)
* #349

**Comment by sonots** [comment]
https://github.com/sonots/embulk-parser-none and https://github.com/sonots/embulk-formatter-single_value are available now (their names were taken from similar Fluentd parser and formatters)

**Comment by frsyuki** [comment]
@sonots solved this issue. Use embulk-parser-none and embulk-formatter-single_value.
