### ISSUE TITLE
Hash will be guessed as string (v0.8.1)

### ISSUE THREAD

**Issue by uu59** [embulk/embulk#379]
`Guess::SchemaGuess.from_hash_records` guessing Array as type: json, Hash as type: string,  etc as below.
Is this an intentional behavior? I think Hash is a json type.

```ruby
p Guess::SchemaGuess.from_hash_records([
  {
    int_in_array: [1,2,3],
    string_in_array: ["a", "b", "c"],
    empty_array: [],
    hash_in_array: [{"id" => 1}, {"id" => 2}],
    hash: {"foo" => "FOO"},
  }
])

# [
#   #<struct Embulk::Column index=0, name=:int_in_array, type=:json, format=nil>,
#   #<struct Embulk::Column index=1, name=:string_in_array, type=:json, format=nil>,
#   #<struct Embulk::Column index=2, name=:empty_array, type=:json, format=nil>,
#   #<struct Embulk::Column index=3, name=:hash_in_array, type=:string, format=nil>,
#   #<struct Embulk::Column index=4, name=:hash, type=:string, format=nil>
# ]
```

**Comment by frsyuki** [comment]
Guess:SchemaGuess.from_hash_records didn't expect nested values. I think this `value.to_s` call needs to be more complex:
https://github.com/embulk/embulk/blob/master/lib/embulk/guess/schema_guess.rb#L40

**Comment by uu59** [comment]
Thanks information.

Looks like trying `JSON.parse(value.to_s)` [at here](https://github.com/embulk/embulk/blob/v0.8.1/lib/embulk/guess/schema_guess.rb#L72).
in Ruby, `[1,2,3].to_s` is a valid JSON string so `[1,2,3]` will be guessed as json,
`{"foo" => "bar"}.to_s` is not so `{"foo" => "bar"}` guessed as string.

My concern is how to guess a hash value on my plugin.
I believe Embulk can handles `{"foo" => "bar"}` value as JSON type, even if SchemaGuess recognize it as string, right?
If so, I'll implement code for hash value to be guessed as json on my plugin.

**Comment by frsyuki** [comment]
array.to_string is not always valid JSON string because the array may include Hash.
SchemaGuess should be improved to support Hash.

**Comment by frsyuki** [comment]
@uu59 Does #384 fixes this issue?

**Comment by uu59** [comment]
Looks good! :+1:
