### ISSUE TITLE
Automate incrementing version number and releasing tasks

### ISSUE THREAD

**Issue by frsyuki** [embulk/embulk#42]
As this commit shows, creating a new release is complicated:
https://github.com/embulk/embulk/commit/24cc1935ff2fba064d9747b01a05777f3ae0508f

1. increment version numbers at pom.xml and embulk-*/pom.xml
2. increment version number at README.md
3. increment version number at build.gradle
4. increment version number at lib/embulk/version.rb
6. git commit -am v0.2.1
7. git tag v0.2.1
8. ./gradlew bintrayUpload
9 rake
10. go to bintray and upload embulk-0.2.1.jar manually
11. gem push pkg/embulk-0.2.1.gem
12. git push && git push --tags

I want to make them as like this:

1. run `rake set_verson 0.2.1` (runs step 1,2,3,4)
2. git commit -am v0.2.1
3. git tag v0.2.1
4. ./gradlew bintrayUpload  (runs step 8, 9, 10)
5. gem push pkg/embulk-0.2.1.gem  (if possible, bintrayUpload should also do this)
6. git push && git push --tags

**Comment by frsyuki** [comment]
new `release` task does almost everything.
The remaining task is to add another gradle task to increment version number at `build.gradle`, `lib/embulk/version.rb`, and `README.md`.

**Comment by hiroyuki-sato** [comment]
Anyone, Please port this code to gradle 
https://gist.github.com/hiroyuki-sato/ee45d92193570411c952

**Comment by frsyuki** [comment]
./gradlew set_version -Pto=VERSION
