### ISSUE TITLE
Add example documentation about EmbulkEmbed.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#421]
Missing documentation about EmbulkEmbed.

From ([Twitter](https://twitter.com/nora96o/status/724566782955016192)) (Japanese)
## Sample Source

``` Java
import java.io.File;
import org.embulk.EmbulkEmbed;
import org.embulk.EmbulkEmbed.Bootstrap;
import org.embulk.config.ConfigLoader;
import org.embulk.config.ConfigSource;

public class EmbulkEmbedTest {
    public static void main(String[] args) throws Exception {
        Bootstrap bootstrap = new EmbulkEmbed.Bootstrap();
        EmbulkEmbed embulk = bootstrap.initializeCloseable();
        try {
            ConfigLoader loader = embulk.newConfigLoader();
            ConfigSource source = loader.fromYamlFile(new File(args[0]));
            embulk.run(source);
        } finally {
            embulk.destroy();
        }
    }
}
```
## Execution example.

You need to set GEM_HOME environment variable.

Linux/OSX/*BSD

```
export GEM_HOME=/embulk/.embulk/jruby/2.2.0
java -classpath .;embulk.jar EmbulkEmbedTest test.yml
```

Windows

```
set GEM_HOME=/embulk/.embulk/jruby/2.2.0
java -classpath .;embulk.bat EmbulkEmbedTest test.yml
```

[Reference](http://hito4-t.hatenablog.com/entry/2015/12/24/170233) (Japanese)

**Comment by chiyoung0258** [comment]
When I use this, get these errors, error messages are below. (with embulk-core-0.8.16)
@hiroyuki-sato , would you explain what is wrong?

1) No implementation for java.util.Set<org.embulk.plugin.PluginType> annotated with @org.embulk.exec.ForGuess() was bound.
  while locating java.util.Set<org.embulk.plugin.PluginType> annotated with @org.embulk.exec.ForGuess()
    for parameter 1 at org.embulk.exec.GuessExecutor.<init>(GuessExecutor.java:69)
  while locating org.embulk.exec.GuessExecutor

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at org.embulk.guice.InjectorProxy.getInstance(InjectorProxy.java:113)
        at org.embulk.EmbulkEmbed.<init>(EmbulkEmbed.java:130)
        at org.embulk.EmbulkEmbed$Bootstrap.build(EmbulkEmbed.java:116)
        at org.embulk.EmbulkEmbed$Bootstrap.initializeCloseable(EmbulkEmbed.java:96)

**Comment by hiroyuki-sato** [comment]
Hello, @chiyoung0258 

Could you try to this example?
https://github.com/hiroyuki-sato/embulkembed_test

It worked with Embulk 0.8.16.

**Comment by chiyoung0258** [comment]
It works. thanks!!!

**Comment by dmikurube** [comment]
`EmbulkEmbed` is no longer recommended for use.
