### ISSUE TITLE
Impossible to download Embulk : File not found 

### ISSUE THREAD

**Issue by puckel** [embulk/embulk#427]
Hi,

> % curl -IL http://dl.embulk.org/embulk-latest.jar
> HTTP/1.1 302 Found
> Server: Cowboy
> Date: Fri, 13 May 2016 07:57:47 GMT
> Connection: keep-alive
> Location: https://dl.bintray.com/embulk/maven/embulk-0.8.9.jar
> X-Content-Type-Options: nosniff
> Content-Length: 0
> Via: 1.1 vegur
> 
> HTTP/1.1 404 Not Found
> Server: nginx
> Date: Fri, 13 May 2016 07:57:47 GMT
> Content-Type: application/octet-stream
> Content-Length: 0
> Connection: keep-alive

Thanks

**Comment by hiroyuki-sato** [comment]
@puckel 

Please use embulk-0.8.8 until 0.8.9 download ready.
You can download embulk-0.8.8 from this URL.
https://dl.bintray.com/embulk/maven/embulk-0.8.8.jar

**Comment by frsyuki** [comment]
thank you for reporting. Somehow release 0.8.9 was created but embulk-0.8.9.jar was not uploaded on bintray. fixed.
