### ISSUE TITLE
"embulk-output-bigquery" plugin installation is failed on Embulk 0.8.10

### ISSUE THREAD

**Issue by runtakun** [embulk/embulk#450]
"embulk-output-bigquery" plugin installation is failed on latest version (0.8.10) of Embulk. I could install successfully on the previous version (0.8.9).

The procedure is as following:

```
# curl -o /usr/local/bin/embulk --create-dirs -L "http://dl.embulk.org/embulk-latest.jar
# chmod +x /usr/local/bin/embulk
# embulk gem install embulk-output-bigquery

Embulk v0.8.10
Successfully installed uber-0.0.15
Successfully installed representable-2.3.0
Successfully installed retriable-2.1.0
Successfully installed addressable-2.4.0
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
Successfully installed hurley-0.2
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.9.2
Successfully installed little-plugger-1.1.4
Successfully installed multi_json-1.12.1
Successfully installed logging-2.1.0
Successfully installed jwt-1.5.4
Successfully installed memoist-0.14.0
Successfully installed os-0.9.6
Successfully installed signet-0.7.3
Successfully installed googleauth-0.5.1
ERROR:  While executing gem ... (NoMethodError)
    undefined method `jar_path' for Gem:Module
```

The build environment is:

```
# java -version

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

This Dockerfile will reproduces this error:
https://github.com/runtakun/embulk_docker_test

I already reported the same issue to "embulk-output-bigquery", too.

Thanks,

**Comment by muga** [comment]
Reproduced same issue.
https://gist.github.com/muga/f36b753eafec465b1169bad448a6ec1e

```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `jar_path' for Gem:Module
	/Users/muga/.embulk/bin/embulk!/embulk/command/embulk_run.rb:344:in `block in ruby'
	uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/installer.rb:552:in `shebang'
... ... 
```

**Comment by muga** [comment]
@runtakun Except embulk-output-bigquery, if you know other plugins that fails during the installation, please let us know.

I tried to install some output plugins written in both of Java and Ruby but, I could install them exception bigquery output. For example, embulk-output-redis was successfully installed.
https://gist.github.com/muga/eee8ebe794f959227a1887587e9dcc53

**Comment by hiroyuki-sato** [comment]
I commented https://github.com/embulk/embulk-output-bigquery/issues/55

``jar_path`` method defined in jruby-9.0.4.0

https://github.com/jruby/jruby/blob/b9fb7aaad77872f08bad7e64ecfa4c481aa3289e/lib/ruby/stdlib/rubygems/defaults/jruby.rb#L34-L39

But not defined in latest jruby(9.1.2.0)
https://github.com/jruby/jruby/blob/master/lib/ruby/stdlib/rubygems/defaults/jruby.rb

**Comment by hiroyuki-sato** [comment]
``jar_path`` method was removed by this commit.
https://github.com/jruby/jruby/commit/fa4846f2c12fef66b31f0973cc58c66fb30cb4fa

**Comment by hiroyuki-sato** [comment]
The ``jar_path`` method is used by some classes.

So simply fix is define it.
For example,

But I think the file place  ``lib/embulk/rubygems.rb`` isn't good.

Could you tell me a better way?

```diff
--- a/lib/embulk/command/embulk_run.rb
+++ b/lib/embulk/command/embulk_run.rb
@@ -1,4 +1,5 @@
 require 'embulk'
+require 'embulk/rubygems'
 
 module Embulk
   def self.run(argv)
diff --git a/lib/embulk/rubygems.rb b/lib/embulk/rubygems.rb
new file mode 100644
index 0000000..322fbf6
--- /dev/null
+++ b/lib/embulk/rubygems.rb
@@ -0,0 +1,8 @@
+module Gem
+  def self.jar_path(p)
+    path = p.sub(/^file:/, "").sub(/!.*/, "")
+    path = path.sub(/^\//, "") if win_platform? && path =~ /^\/[A-Za-z]:/
+    path
+  end
+end
+
```

**Comment by runtakun** [comment]
@muga I do not know other plugin which causes this error. I changed ambiguous title of this issue.

**Comment by runtakun** [comment]
@hiroyuki-sato I could install successfully by your patch.

**Comment by hiroyuki-sato** [comment]
Thank you for testing.

**Comment by hiroyuki-sato** [comment]
@runtakun 
I created PR for fix this issue. 
https://github.com/embulk/embulk/pull/451
Please wait for next release.

**Comment by frsyuki** [comment]
#452 fixes this issue.

**Comment by frsyuki** [comment]
embulk v0.8.11 includes this fix.
