### ISSUE TITLE
Adding filepath to record

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk#473]
New feature request;
Fluentd in_tail plugin has path_key feature where it inserts currently processed filename into event record.

Would it possible to have something similar for embulk? (Not quite sure where this should actually go, file input?)

**Comment by hiroyuki-sato** [comment]
An another user require the same feature.
I would like to share the previous discussion. 

The Embulk file input plugin reads a file from a local file system, S3, FTP, SFTP and so on. 
Those files are sometimes encoded and archived (tar,gzip,zip or so on).

So If you want to get the filename, you needs extract
files into a temporary directory and get it. 

As the result, load speed will slow, and data size will be bigger.

In my opinion(An Embulk user), A new embulk input plugin may solve this requirement.
I'll appreciate if you share your use case. 

Best regards.

**Comment by kakoni** [comment]
Ok, understand the design rationales now. I can actually implement my usecase differently by using workflows (perhaps digdag to drive embulk and then doing modifications in database afterwards succesfull import). Closing this.
