### ISSUE TITLE
Logo Without Text part.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#482]
Related #460 

New logo really Cool!!.

By the way, We need logo without text part.
Please update the new logo image without text part.
For example. 

![](https://www.treasuredata.com/assets/resources/td-jp-fluentd-embulk-class-7c04156df8a3ad259984bc103d498b50.jpg)

**Comment by toru-takahashi** [comment]
I think this PR will satisfy your request.
https://github.com/embulk/embulk/pull/655

**Comment by hiroyuki-sato** [comment]
Thanks!
