### ISSUE TITLE
Output into one single excel/csv file

### ISSUE THREAD

**Issue by Olaktal** [embulk/embulk#510]
Hello,

Sometimes people ask me data and the only way I can give them is by sending them data through csv or excel file. For now I can export data into csv files but I can't manage how to put them into one single csv/excel file. Is it possible ?

Thanks
Vincent

**Comment by hiroyuki-sato** [comment]
Please try. 
https://github.com/embulk/embulk/issues/501#issuecomment-257837550

**Comment by Olaktal** [comment]
Perfect ! Thanks @hiroyuki-sato
