### ISSUE TITLE
use nanosec for ExecSession timestamp

### ISSUE THREAD

**Issue by ukisoft** [embulk/embulk#529]
Using embulk, sometimes there is error because session are same.
So, I would like to use nanosec for ExecSession timestamp.

I found TODO. Could I know when it will be improved?

https://github.com/embulk/embulk/blob/d807e6aaae9bb02b71d9aae355b1298356ed26b5/embulk-core/src/main/java/org/embulk/spi/ExecSession.java
```
        public ExecSession build()
        {
            if (transactionTime == null) {
                transactionTime = Timestamp.ofEpochMilli(System.currentTimeMillis());  // TODO get nanoseconds for default
            }
            return new ExecSession(injector, transactionTime, Optional.fromNullable(loggerFactory));
        }
```

**Comment by hiroyuki-sato** [comment]
Could you tell me more detail about the same session error?
Do you have any logs about it?

I asked about @frsyuki this issue.  
He said that nanoseconds are better than milli seconds.
But there is no method like `System.currentTimeMillis` for nano seconds.

**Comment by ukisoft** [comment]
Thank you for your comment.

I use embulk from MySQL to Treasure Data with digdag.
And I'm sorry, I use embulk on my company, so I can't give you our full logs.
Instead of that, I copied some logs at end of this message.
I hope it helps you to improve embulk.

Anyway, I asked also Treasure Data support officer before about it.
Fortunately they answered last week, and they recommend session configuration of td plugin: https://github.com/treasure-data/embulk-output-td.

I will try it. Thank you.


Logs are like this. 
Session is dummy, but it seems that same session caused errors.

----- first embulk log partially -----
2016-11-07 06:45:13.817 +0900 [INFO] (0001:transaction): Create bulk_import session embulk_20161106_123456_789000000
2016-11-07 06:45:14.152 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2016-11-07 06:45:14.367 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2016-11-07 06:45:19.563 +0900 [INFO] (0001:cleanup): Deleting bulk import session 'embulk_20161106_123456_789000000'
org.embulk.exec.PartialExecutionException: com.treasuredata.client.TDClientHttpNotFoundException: [TARGET_NOT_FOUND] [404:Not Found] API request to /v3/bulk_import/show/embulk_20161106_123456_789000000 has failed: Resource not found

----- second embulk log partially -----
2016-11-07 06:45:14.222 +0900 [INFO] (0001:transaction): Create bulk_import session embulk_20161106_123456_789000000
2016-11-07 06:45:14.572 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2016-11-07 06:45:15.057 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2016-11-07 06:45:15.355 +0900 [INFO] (0001:cleanup): Deleting bulk import session 'embulk_20161106_123456_789000000'
org.embulk.exec.PartialExecutionException: com.treasuredata.client.TDClientHttpException: [INVALID_INPUT] [422:Unprocessable Entity] API request to /v3/bulk_import/perform/embulk_20161106_123456_789000000 has failed: Bulk import has already started performing.

**Comment by hiroyuki-sato** [comment]
@ukisoft Thank you for the comments!.

* There is no method to get nanosecond time easily on the Java7 environment.
* This is the embulk-output-td plugin specific issue. And it can solve that problem with plugin configuration. 

Ref: [Twitter](https://twitter.com/hiroysato/status/823356137714028545) (Japanese Text)

**Comment by muga** [comment]
@ukisoft @hiroyuki-sato Sorry for the late response.

**Comment by muga** [comment]
@ukisoft @hiroyuki-sato this is embulk-output-td issue. I should move and talk about it on embulk-output-td repo. But, could you tell me that multi bulk_import sessions are created for single table in parallel? We might be able to change the name of bulk_import session from 'embulk_xxx_xxx_xxx' to 'embulk_mytable_mydb_xxx_xxx_xxx' if your session name conflict could be mitigated.

**Comment by ukisoft** [comment]
Thank you for your advice.
The situation that those bulk_import sessions were created is;

- same database on treasure data
- difference table
- on one digdag job (written in same digdag file)
- use _parallel execution

**Comment by ukisoft** [comment]
We collect a lot of data for data warehouse every hour through treasure data.
Then it sometimes happens that a few embulk work at the same time.
It's not good for performance, so recently we avoid parallel execution, and try to control schedule of job.

**Comment by toru-takahashi** [comment]
@ukisoft  You can use "session" parameter in embulk-output-td to avoid generating same session name.
For example, your embulk.yml.liquid should be...

```
out:
  type: td
  apikey: <your apikey>
  endpoint: api.treasuredata.com
  database: my_db
  table: my_table
  time_column: created_at
  session: "embulk_my_table_{{env.xxxx}}"
```

Ex. http://qiita.com/hiroysato/items/6d8542556d0dd0adfe8b#%E8%A8%AD%E5%AE%9A%E4%BE%8B-1

**Comment by ukisoft** [comment]
Thank you for your advice.
I will try it :)

**Comment by muga** [comment]
I just wanted to announce that embulk-output-td 0.3.14 was released. In 0.3.14, since bulk_import session name is generated by random UUID, the session name conflict might not occur.

https://rubygems.org/gems/embulk-output-td/versions/0.3.14

**Comment by ukisoft** [comment]
Thank you for your announce!! I will try it :) :)
