### ISSUE TITLE
[v2] Stop providing embulk.gem

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#566]
https://docs.google.com/document/d/1f-ziuHY4fXXmSLNHCXP3AAXUajEyPMLQAvH4jgTjpGg/edit

**Comment by hiroyuki-sato** [comment]
@dmikurube Just FYI. 

I don't see much times `require 'embulk'` from many source codes.
Today, I found it. I just want to share my experience.

* [embulk と AWS Lambda でサーバーレスデータ連携](http://qiita.com/mitoma/items/354a114fd8321108499e) (Japanese text) (The Embulk and AWS Lambda for serverless data cooperation. )
* [AwsLambdaExecutor.java](https://github.com/mitoma/embulk-awslambda-packager/blob/master/src/main/java/in/tombo/embulk/AwsLambdaExecutor.java#L121-L123)

They are using EmbulkEmbed on the JRuby.

**Comment by dmikurube** [comment]
@hiroyuki-sato Thanks for the information! That's really helpful for making final decisions on this.

**Comment by dmikurube** [comment]
It is finally done in v0.9.0.
