### ISSUE TITLE
LocalFile#getPath raises InvalidPathException in Windows Platform

### ISSUE THREAD

**Issue by kazup0n** [embulk/embulk#576]
LocalFile#getPath raises InvalidPathException in Windows Platform.

Detailed message in my env is below.
```
       at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 78: C:
sers\ADMINI~1\AppData\Local\Temp\3\embulk\2017-03-27 07-44-47.729 UTC\0018:tas
0000_3955419062330253204.tmp
       at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
       at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
       at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
       at sun.nio.fs.WindowsPath.parse(Unknown Source)
       at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
       at java.io.File.toPath(Unknown Source)
       at org.embulk.spi.unit.LocalFile.getPath(LocalFile.java:76)
       at org.embulk.spi.unit.LocalFile.getPath(LocalFile.java:70)
       at org.embulk.output.sftp.SftpFileOutput$4.apply(SftpFileOutput.java:33

       at org.embulk.output.sftp.SftpFileOutput$4.apply(SftpFileOutput.java:33

       at com.google.common.base.Present.transform(Present.java:71)

Error: java.nio.file.InvalidPathException: Illegal char <:> at index 78: 
C:\Users\ADMINI~1\AppData\Local\Temp\3\embulk\2017-03-27 07-44-47.729 UTC\0018:task-000
0_3955419062330253204.tmp
```
In [`org.embulk.exec.SetCurrentThreadName`](https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/exec/SetCurrentThreadName.java#L14), using`:(semicoron)` as a separator between thread name and thread id causes this.

Could we replace separator char with some _windows-path-safe char_ (e.g. `-`, `_` and so on) ??

**Comment by kazup0n** [comment]
as [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) says,  we can't use these characters in path in windows.

```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

**Comment by hiroyuki-sato** [comment]
@kazup0n 
Thank you for the writing this issue. 
Can you show me your configuration?
I suspect that this problem is the `embulk-output-sftp` specific issue. 

If you change the output plugin to `null`, Can you solve this issue?

```yaml
out:
  type: "null" # !Caution! Need double quote.
```

**Comment by hiroyuki-sato** [comment]
And more more thing, It is better to replace `:` character to Windows safe character too.

**Comment by kazup0n** [comment]
here's my conf. and it isn't reproduced when output type is set to `"null"`.

```
out:
  type: sftp
  host: ec2-*****
  port: 22
  user: ec2-user
  secret_key_file: ./my_pem_file.pem
  user_directory_is_root: false
  timeout: 600
  path_prefix: /home/ec2-user/{{path_prefix}}_{{today}}.
  file_ext: csv
  sequence_format: ""
  formatter:
    type: csv
    header_line: true
    charset: UTF8
    newline: CRLF
    quote_policy: ALL
```

As you said, It is occurred when using `embulk-output-sftp`.

I found that error raises in [`SftpFileOutput#initializeFsOptions`](https://github.com/civitaspo/embulk-output-sftp/blob/master/src/main/java/org/embulk/output/sftp/SftpFileOutput.java#L88) and [`SftpFileOutput#localFileToPathString`](https://github.com/civitaspo/embulk-output-sftp/blob/master/src/main/java/org/embulk/output/sftp/SftpFileOutput.java#L333) in where secret key is read with `LocalFile#getPath`.

should I report to `embulk-output-sftp` first ??

**Comment by hiroyuki-sato** [comment]
Thank you for investigating.
I'll write this issue on the `embulk-output-sftp` project.

**Comment by kazup0n** [comment]
@hiroyuki-sato 
I appreciate your quick help.

**Comment by sakama** [comment]
@kazup0n I'm collaborator of embulk-output-sftp.

embulk-output-sftp supports to embed secret_key_file content at config.
You can probably to avoid this failure using above method as a workaround.
I'm sorry but I don't have Windows machine and I've not tried.
```
out:
  type: sftp
  ...
  secret_key_file:
    content |
      -----BEGIN RSA PRIVATE KEY-----
      ABCDEFG...
      HIJKLMN...
      OPQRSTU...
      -----END RSA PRIVATE KEY-----
  ...
```

**Comment by kazup0n** [comment]
@sakama 
Thanks for the workaround. 
But I've already tried the way and it results same error.

In `LocalFile#getPath` 

a) When path was `null`  
the error occurs by calling `tempFileSpace.createTempFile().toPath()`
https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/spi/unit/LocalFile.java#L75

It is because of `:` in path generated in `org.embulk.exec.SetCurrentThreadName`.


b) When path was not null
It seems that the error won't be thrown. 
But it will be thrown in my case...
(Maybe path was set in https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/spi/unit/LocalFileSerDe.java#L109)

I'm working on case (b) ...

**Comment by hiroyuki-sato** [comment]
@kazup0n 

#589 will fix this issue. Please wait for next release. 
And close this issue when the problem solved.

**Comment by hiroyuki-sato** [comment]
@kazup0n 

Embulk 0.8.19 released!.
This issue fixed. Please try it and close this issue if it works well.

**Comment by kazup0n** [comment]
OK, I'm trying.

**Comment by kazup0n** [comment]
My problem with `embulk-output-sftp` is fixed . Thankyou !
