### ISSUE TITLE
Change temporary filename format for Windows safe. 

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#580]
The [`createTempFile`](https://github.com/embulk/embulk/blob/c6a340531cd37fd8f8b99d89a140b3a9a103659b/embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java#L28-L31) method use [Thread name](https://github.com/embulk/embulk/blob/c6a340531cd37fd8f8b99d89a140b3a9a103659b/embulk-core/src/main/java/org/embulk/exec/SetCurrentThreadName.java#L14). 
It contains `:` character and, It does not Windows safe. [detail](https://github.com/embulk/embulk/issues/576#issuecomment-289380573)

As a result. Some plugin does not work correctly.  [embulk-output-sftp](https://github.com/embulk/embulk/issues/576#issue-217163610)

The `createTempFile` should return multi-platform safe path name.

We also need to consider multiuser-safe temporary path. 
See also this issue #423

Ref: [embulk-output-sftp issue](https://github.com/embulk/embulk-output-sftp/issues/27#issuecomment-289463049)

**Comment by hiroyuki-sato** [comment]
@muga @dmikurube 

I talked @sakama  about this issue.(Except #423) ([Twitter](https://twitter.com/hiroysato/status/847696011187204097) Japanese text)

Which is better? Or do you have another idea?

1. Change thread name itself. Like [`%04#`](https://github.com/embulk/embulk/blob/c6a340531cd37fd8f8b99d89a140b3a9a103659b/embulk-core/src/main/java/org/embulk/exec/SetCurrentThreadName.java#L14)
  * Pros: simple. 
  * Cons: break compatibility (I don't know about impact.) 
2. Replace temporary filename character only [Fix #580, replace ':' to '_' for Windows.](https://github.com/hiroyuki-sato/embulk/commit/118a956a76424bf102b6063511996fc4833fbbb2)
  * Pros: No need to care about compatibility. 
  * Cons: Uncool.

**Comment by muga** [comment]
I prefer 2nd idea because:

- We don't need to change thread names. Plugins basically don't need to care of multi-threading under Embulk concept. But, I don't know that any plugins are not implemented by using the thread names. 
- A temp file doesn't need to be same name as the thread's.

**Comment by hiroyuki-sato** [comment]
@muga Thank you for the comment. 

I'll test https://github.com/hiroyuki-sato/embulk/commit/118a956a76424bf102b6063511996fc4833fbbb2 at next week on a Windows. 

Please let me know If I should change any character instead of `_`;

**Comment by dmikurube** [comment]
@hiroyuki-sato 2 looks better to me as well. I don't see benefits to break compatibilities there.
