### ISSUE TITLE
Use MANIFEST instead of embulk.properties?

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#596]
We've implemented #560 to embed Embulk versions in `embulk.properties`, but I thought we should have used JAR manifest instead of our own original properties file.

Will update the decision, but let me just share for now... Ping me if we have plans to release new Embulk versions soon. @muga

**Comment by muga** [comment]
> I thought we should have used JAR manifest instead of our own original properties file.

Sounds good to me. Let's replace with MANIFEST.MF. About next release, I can wait one week at least.

**Comment by dmikurube** [comment]
Done.
