### ISSUE TITLE
Update JRuby 9.1.8.0

### ISSUE THREAD

**Issue by muga** [embulk/embulk#600]
@hiroyuki-sato mentioned upgrading JRuby on https://github.com/embulk/embulk/pull/591

> By the way, JRuby 9.1.8.0 released at 6/Mar/2017
> http://jruby.org/2017/03/06/jruby-9-1-8-0.html
> It fixed many issues.

**Comment by hiroyuki-sato** [comment]
The version 9.1.8.0 is Ruby 2.3.1 compatible. 
It is the same 9.1.5.0 which is used in Embulk 0.8.18.

It may don't break compatibility like the
Embulk 0.8.9 to 0.8.10.
http://www.embulk.org/docs/release/release-0.8.10.html
It updated Ruby 2.2.0 to 2.3.0.

```
[1] pry(main)> JRUBY_VERSION
=> "9.1.8.0"
[2] pry(main)> RUBY_VERSION
=> "2.3.1"
```

**Comment by hiroyuki-sato** [comment]
Just note.

@sonots hit this issue on the embulk [0.8.6](http://www.embulk.org/docs/release/release-0.8.6.html). 
https://github.com/jruby/jruby/issues/3670

He forked and downgraded JRuby to 9.0.4.0 for a while. 

https://twitter.com/sonots/status/710759273312030720
https://twitter.com/sonots/status/710763938074333184

**Comment by muga** [comment]
Thank you for sharing that. According to https://github.com/jruby/jruby/issues/3670, it seems that this issue was fixed on v9.1.0.0. Embulk v0.8.18 uses JRuby v9.1.5.0 so, v9.1.5.0 should be ok for https://github.com/jruby/jruby/issues/3670. 

I will care of this after Embulk v0.8.19.

**Comment by hiroyuki-sato** [comment]
@muga thank you for the comment.

I just wanted to note. 
The update will cause another issue just in case, so we need to update it carefully. 
(ex. sonots case. Yes that already fixed.)

Almost same meaning this tweet by muga 
[Twitter](https://twitter.com/muga_nishizawa/status/852791624170053632)

**Comment by dmikurube** [comment]
JRuby has already been upgraded to 9.1.13.0, and 9.1.15.0 in v0.9.0.
