### ISSUE TITLE
Upgrade Jackson v2.8

### ISSUE THREAD

**Issue by muga** [embulk/embulk#605]
We should upgrade recent version of Jackson like v2.8 if we don't have any concerns. (It seems that v2.9 will be released at Mar, 2017)

**Comment by hiroyuki-sato** [comment]
Mar -> May? 

I was wondering why it isn't the latest version. 
I don't have any concern.

**Comment by muga** [comment]
> (It seems that v2.9 will be released at Mar, 2017)
Sorry, 2.9.0.pr2 was released at Mar, 2017. 

https://github.com/FasterXML/jackson-core/releases
Since it seems that 2.9 is still pre-release, I was going to test 2.8 for Embulk.

**Comment by muga** [comment]
As first step, I try to update v2.6.7. https://github.com/embulk/embulk/pull/615

**Comment by dmikurube** [comment]
We'll upgrade to later ones after v0.11 gets stable.
