### ISSUE TITLE
Support geospatial type

### ISSUE THREAD

**Issue by chie8842** [embulk/embulk#612]
It's very useful if geometry data type is supported at embulk.

**Comment by hiroyuki-sato** [comment]
Hello, @chie8842 

I'm not familiar about GIS. 
Please tell maintainers about your problem. 

I'm interested in GIS area personally. 
* Is geospatial particular data format?

There are some plugins about GIS data. 
Does these plugins are helpful for you?
* [embulk-filter-reverse_geocoding](https://rubygems.org/gems/embulk-filter-reverse_geocoding)
* [embulk-formatter-geojson](https://rubygems.org/gems/embulk-formatter-geojson)

**Comment by chie8842** [comment]
Oh, I didn't know about embulk-filter-reverse_geocoding.
OK, my problem is solved.
I close the issue.
Thank you.
