### ISSUE TITLE
Support digest filter plugin in embulk-standards

### ISSUE THREAD

**Issue by muga** [embulk/embulk#616]
The proposed filter plugin allows users to convert input data into the message digests by column basis. When different persons or teams manage input source and output destination, a part of input data need to be converted by several reasons to transfer the data from input to output. In that case, the plugin would be useful.

I roughly checked that such plugin exists and found [embulk-filter-hash](https://github.com/kamatama41/embulk-filter-hash). If such filter plugin could be supported as embulk-standards, I will ask the author to help the porting with me first. If not, I will implement it.

How about it?

**Comment by hiroyuki-sato** [comment]
It's a good idea!. 
The [embulk-filter-mask](https://github.com/beniyama/embulk-filter-mask) is a similar plugin. 
This plugin support mask JSON data with JSONPath. 
(But it's only masked data like `***@example.com`, not digest)

Both plugins authors are speakers on the next Meetup by the way.

**Comment by dmikurube** [comment]
We have no plans to have more "standard" plugins as of now.
