### ISSUE TITLE
Add InputPlugin#guess

### ISSUE THREAD

**Issue by komamitsu** [embulk/embulk#68]
In https://github.com/komamitsu/embulk-plugin-redis, I want to use "bin/embulk guess" command to guess a schema in Redis and generate schema information automatically as much as possible. Of cause it's not a complete schema because Redis is schema-less, though.

To achieve that, I think we need to add InputPlugin#guess method like this:

```
  class InputXxxxx < InputPlugin
    def self.guess(config)
      x = Xxxxx.connect(
              config.param('host', :string, :default => 'localhost'),
              config.param('port', :integer, :default => 8888))
      xs = x.get((0...x.size).select{|i| i % 10 == 0})
      // Checking the schemas of `xs'...
          :
      cols << Column.new(idx, schema_name, schema_type)
          :
      cols
    end
```

**Comment by frsyuki** [comment]
v0.5 will include this SPI.

**Comment by komamitsu** [comment]
`input-guess` branch worked well on  https://github.com/komamitsu/embulk-plugin-redis. Thanks!
