### ISSUE TITLE
[Propose] What about using Milestone for tracking PR and issues?

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#693]
Sometime I would like to know "what version is fixed this issue?".
Milestone feature is a better way. 
What about using Milestone for version tracking PR and issues?

Example
https://github.com/embulk/embulk-input-jdbc/milestones?state=closed
https://github.com/jruby/jruby/milestones

**Comment by muga** [comment]
Agree. Do you have any concerns? @dmikurube

**Comment by dmikurube** [comment]
I have no concerns. Are we using milestones instead of "Plan 0.8.XX" issues?

**Comment by dmikurube** [comment]
Created a milestone for a trial. What do you think?

https://github.com/embulk/embulk/milestone/2

**Comment by muga** [comment]
Looks nice :-)

**Comment by hiroyuki-sato** [comment]
Looks nice 👍 Thank you!.
