### ISSUE TITLE
[RFC] Update gradle to 4.0

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#709]
@muga @dmikurube 

* What do you think to update gradle to 4.0.
* If it's OK,
  * when is a good time for updating?
  * Please review this PR ~~#698~~. #710
  * Especially, how can we migrate about [`Task.leftShift(Closure)` depreciation?](https://github.com/embulk/embulk/pull/698#issuecomment-312422241)

This issue isn't an important.

I tried to implement gradle 4.0 migration with the following reason. 

* I seems The build speed of gradle 4.0 faster than 3.x. 
* Gradle 4.0 simpler than 3.0? [Twitter](https://twitter.com/muga_nishizawa/status/880701974118883328) (Written in Japanese).

Best regards.

**Comment by dmikurube** [comment]
@hiroyuki-sato I'm basically positive to upgrade, but:

- Let's get it done after upcoming big updates (Timestamp, etc) are done. 4.0 can be a big change. We don't want to be confused.
- For `Task.leftShift(Closure)`, it may be worth to do in `embulk migrate`, but I'm not keen on implementing it. It's easy to do in each plugin.

**Comment by hiroyuki-sato** [comment]
I separate #698 into multiple PRs.

It depends on the previous PR. I request PR one by one.

* Add an `executable` flag for Migrator. [#710]
* Update Gradle 4.0 [[update_gradle_4_0](https://github.com/hiroyuki-sato/embulk/tree/update_gradle_4_0) branch]
* Add `Task.leftShift(Closure)` warning.  [[task_left_shift_deprecated_caution](https://github.com/hiroyuki-sato/embulk/tree/task_left_shift_deprecated_caution) branch]

**Comment by hiroyuki-sato** [comment]
Gradle has been updated to 4.1.0.  #780, #781, #782
