### ISSUE TITLE
some commands exit with status 1 even if it doesn't cause an error

### ISSUE THREAD

**Issue by yuskesh** [embulk/embulk#71]
embulk exits with status 1 when version(`--version`) or help(`--help`) command is executed.
It would be great if it exits with 0 in such cases.

**Comment by frsyuki** [comment]
do you have specific examples when you want to get exit code=0 especially with `--help` option?

**Comment by frsyuki** [comment]
I changed --version to return 0. Thank you!

**Comment by yuskesh** [comment]
Thank you for fixing the issue!

Maybe there is no useful case with `--help` option.
I just found the issue when I tried to check embulk is actually available or not on a server. Then I tried with other programs like java/ruby/python and found those programs exited with 0 when those were executed with `--help`.

**Comment by frsyuki** [comment]
I see. That's good to know. Please don't hesitate to reopen this issue if you find specific examples.
Thank you!
