### ISSUE TITLE
CSV Parser does not support full Ruby datetime format

### ISSUE THREAD

**Issue by mjalkio** [embulk/embulk#796]
According to the documentation at http://www.embulk.org/docs/built-in.html#csv-parser-plugin "The Timestamp format refers to Ruby strftime format."

However, I am trying to parse datetimes in this format `2017-09-19 13:39:15.139396-07:00` (this is default string formatting from Python) using `%Y-%m-%d %H:%M:%S.%6N%Z`, and it does not work. I believe that `%6N` is not supported.

I believe you should add additional documentation to explain that you're not actually using the Ruby methods directly and you've built your own parser (https://github.com/embulk/embulk/blob/master/embulk-jruby-strptime/src/main/java/org/embulk/spi/time/StrptimeParser.java)

**Comment by dmikurube** [comment]
@mjalkio Thanks for your feedback! Will have a deeper look. Cc: @muga

**Comment by dmikurube** [comment]
Sorry to be late. Let me leave my view. TL;DR, we should just update the document like you mentioned, @mjalkio.

The original Ruby has had different format rules for formatting and parsing. `Time.strftime` accepts numeric prefix like `%6N` while `Time.strptime` does not accept. It was discussed at: https://bugs.ruby-lang.org/issues/11220 (in Japanese, though)

We're (and should be) actually following original Ruby's behavior for formatting and parsing. The description "The Timestamp format refers to Ruby strftime format." is really wrong in terms of parsing. We should just mention it follows `strptime`'s format, and it is different from `strftime`'s.

Embulk's `StrptimeParser` is trying to emulate the original Ruby `Time.strptime`. If it is not working like `Time.strptime`, it'd be recognized as a bug to be fixed.

@muga Any more thoughts do you have?

**Comment by mjalkio** [comment]
Makes sense, I pushed a PR with the proposed change to the language.
