### ISSUE TITLE
Use Ruby's timezone names instead of Joda-Time's

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#833]
While I was walking-through and trying to refactor our Ruby-compatible date/time parser, I'm afraid I found that we may not using Ruby's timezone names (`TimeZoneConverter`), but using Joda-Time's.

* https://github.com/embulk/embulk/blob/v0.8.36/embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java#L188
* https://github.com/embulk/embulk/blob/v0.8.36/embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java#L58-L88

@muga Can you check it? If it's true, I'd fix it throughout my refactoring.

**Comment by muga** [comment]
Yea, it seems that it's using joda-time :-0

**Comment by dmikurube** [comment]
@muga Hmm, I found that this has been like this for a very long time...

* https://github.com/embulk/embulk/blame/v0.8.36/embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java#L188
* https://github.com/embulk/embulk/blame/v0.8.36/embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java#L58-L88

It may be hard to change this from now, but at the same time, I've found that some Ruby-style timezones are rejected by the current implementation.

```
org.embulk.spi.time.TimestampParseException: Invalid time zone name 'Thu Jul 29 16:39:41 AMT 1999'
```
* https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/tags/v2_3_1/test/date/test_date_strptime.rb?view=markup#l137

Let's discuss this later.
