### ISSUE TITLE
Print Embulk core's version when executed from EmbulkEmbed

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#882]

**Comment by hiroyuki-sato** [comment]
@dmikurube  It's a good feature.

JFYI. As discussed before, It is better to print Embulk version if a user specifies `--log` option too. 
Should I create another issue?

https://twitter.com/hito4_t/status/761063288390037504 (Written in Japanese)

**Comment by dmikurube** [comment]
@hiroyuki-sato Ah thanks! I was forgetting this issue.

v0.9 should be good time to change this behavior... Will do this.
