### ISSUE TITLE
Deprecate "Update JRuby" in README.md

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#929]
Just reminder. 

https://github.com/embulk/embulk/pull/885#issuecomment-352926644

Remove this part in README.
https://github.com/embulk/embulk#update-jruby

**Comment by dmikurube** [comment]
Done in https://github.com/embulk/embulk/pull/928... :)

**Comment by hiroyuki-sato** [comment]
Oh. Thank you!. :)
