### ISSUE TITLE
 I want to be able to specify JavaVM

### ISSUE THREAD

**Issue by HiroshiFujita** [embulk/embulk#944]
In embulk.bat, since java.exe is directly specified, it is difficult to specify java.exe to use from outside.

In an environment, I want to switch and operate multiple Java VMs, so I do not want to edit JAVA_HOME.

`
java %java_args% -jar %this% %jruby_args% %args%
`

**Comment by hiroyuki-sato** [comment]
Hello, @HiroshiFujita 

May I suggest that you use `/path/to/java -jar embulk.bat` command?

**Comment by dmikurube** [comment]
@hiroyuki-sato Thanks for your follow-up!

@HiroshiFujita As @hiroyuki-sato mentioned, you can just specify the downloaded JAR file for `java -jar`. The file is a little bit tricked, but still a normal JAR file.

**Comment by HiroshiFujita** [comment]
Thank you for the immediate reply.

It worked well in the way of @hiroyuki-sato

**Comment by dmikurube** [comment]
Thanks for reporting the result, @HiroshiFujita. Let me close this issue.
