### ISSUE TITLE
[doc] Update header and footer

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#945]
http://www.embulk.org/docs/index.html

* Header `Embulk 0.8 documentation` -> `Embulk 0.9 documentation`
* Footer `Copyright 2015, Embulk Project` -> `Copyright 2015-2018, Embulk Project`

**Comment by hiroyuki-sato** [comment]
Just reference for improving documentation.

[@shigemk2](https://twitter.com/shigemk2/status/1057589739748880385) introduced me Presto way.

https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/conf.py#L57-L76

**Comment by dmikurube** [comment]
Docs went to https://github.com/embulk/embulk.github.io
