### ISSUE TITLE
Ruby Symbols are converted to String implicitly after passing them to `yield' as a parameter in InputPlugin.transaction

### ISSUE THREAD

**Issue by komamitsu** [embulk/embulk#96]
Ruby Symbols are converted to String implicitly after passing them to `yield` as a parameter in InputPlugin.transaction.

```
module Embulk
  class InputRedis < InputPlugin
    Plugin.register_input('redis', self)
    def self.transaction(config, &control)
      task = {
            :
        :hello => :world
      }
      commit_reports = yield(task, columns, 1)
            :


    def run
      require 'pp'
      pp @task    ==> {...., "hello"=>"world"}
```

I just looked over the source code. `org.embulk.config.ModelManager` uses `com.fasterxml.jackson.databind.ObjectMapper#writeValueAsString` and I guess it converts RubySymbol to just String internally and it's related to the issue.

**Comment by frsyuki** [comment]
#13

**Comment by komamitsu** [comment]
Duplicated
